/**
 * Public landing-page snapshot of Synci's published bank directory.
 *
 * It makes the coverage finder useful before Wollie's Synci Managed App is
 * activated. Replace this snapshot with Synci's authenticated Institutions API
 * once the app is live, because institution availability can change.
 */
export type SynciDirectoryCountry = {
  code: string;
  name: string;
  slug: string;
  bankCount: number;
  banks: readonly string[];
};

export const SYNCI_DIRECTORY_URL = "https://synci.io/banks";
export const defaultSynciCountryCode = "BE";

export const synciDirectoryCountries: readonly SynciDirectoryCountry[] =
  [
  {
    "code": "AT",
    "name": "Austria",
    "slug": "austria",
    "bankCount": 87,
    "banks": [
      "Airwallex",
      "Allgemeine Sparkasse Oberösterreich Bank AG",
      "Bank Austria",
      "Bank Austria - BusinessNet",
      "Bank Austria - UC eBanking Global",
      "Bank99",
      "BAWAG P.S.K.",
      "BKS Bank",
      "BTV Bank",
      "bunq",
      "Die Zweite Wiener Vereins-Sparcasse",
      "Dornbirner Sparkasse Bank AG",
      "easybank BAWAG",
      "Erste Bank der oesterreichischen Sparkassen AG",
      "Erste Group Bank AG",
      "Finom",
      "HSBCnet",
      "Hypo Oberösterreich",
      "ING Wholesale Banking",
      "Kärntner Sparkasse AG",
      "Lienzer Sparkasse AG",
      "Lunar",
      "Marchfelder Bank",
      "Monese",
      "N26 Bank",
      "Neteller",
      "Oberbank",
      "Österreichische Ärzte- und Apothekerbank",
      "PayPal",
      "Paysera",
      "Qonto",
      "Raiffeisen Bank",
      "Revolut",
      "Salzburger Sparkasse Bank AG",
      "Skrill",
      "Soldo",
      "Sparda-Bank",
      "Sparkasse Baden",
      "Sparkasse Bludenz Bank AG",
      "Sparkasse Bregenz Bank AG",
      "Sparkasse der Gemeinde Egg",
      "Sparkasse der Stadt Amstetten AG",
      "Sparkasse der Stadt Feldkirch",
      "Sparkasse der Stadt Kitzbühel",
      "Sparkasse Eferding-Peuerbach-Waizenkirchen",
      "Sparkasse Feldkirchen/Kärnten",
      "Sparkasse Frankenmarkt AG",
      "Sparkasse Hainburg-Bruck-Neusiedl AG",
      "Sparkasse Haugsdorf",
      "Sparkasse Herzogenburg-Neulengbach Bank AG",
      "Sparkasse Horn-Ravelsbach-Kirchberg AG",
      "Sparkasse Imst AG",
      "Sparkasse Korneuburg AG",
      "Sparkasse Kufstein, Tiroler Sparkasse von 1877",
      "Sparkasse Langenlois",
      "Sparkasse Mittersill Bank AG",
      "Sparkasse Muehlviertel-West Bank AG",
      "Sparkasse Mürzzuschlag AG",
      "Sparkasse Neuhofen Bank AG",
      "Sparkasse Neunkirchen",
      "Sparkasse Niederoesterreich Mitte West Ag",
      "Sparkasse Pöllau AG",
      "Sparkasse Pottenstein N.Ö.",
      "Sparkasse Poysdorf AG",
      "Sparkasse Pregarten - Unterweißenbach AG",
      "Sparkasse Rattenberg Bank AG",
      "Sparkasse Reutte AG",
      "Sparkasse Ried im Innkreis-Haag am Hausruck",
      "Sparkasse Salzkammergut AG",
      "Sparkasse Scheibbs AG",
      "Sparkasse Schwaz AG",
      "Sparkasse Voitsberg-Köflach Bankaktiengesellschaft",
      "Steiermärkische Bank und Sparkassen AG",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Volksbank Kärnten",
      "Volksbank Niederösterreich",
      "Volksbank Oberösterreich",
      "Volksbank Salzburg",
      "Volksbank Steiermark",
      "Volksbank Tirol",
      "Volksbank Vorarlberg",
      "Volksbank Wien",
      "Waldviertler Sparkasse Bank AG",
      "Wiener Neustädter Sparkasse",
      "Wise"
    ]
  },
  {
    "code": "BE",
    "name": "Belgium",
    "slug": "belgium",
    "bankCount": 49,
    "banks": [
      "ABN AMRO Bank Commercial",
      "Aion Bank",
      "Airwallex",
      "Argenta",
      "Bank J. Van Breda & Co",
      "Banque CPH",
      "Banque Transatlantique",
      "Banque Triodos",
      "Banx",
      "BBVA",
      "Belfius",
      "Beobank",
      "BNP Paribas Fortis",
      "BNP Paribas Fortis Business",
      "bunq",
      "CBC Banque",
      "Crelan",
      "Deutsche Bank",
      "Ebury",
      "Europa Bank",
      "Finom",
      "Fintro",
      "Fintro Business",
      "Hello bank!",
      "HSBCnet",
      "ING",
      "ING Wholesale Banking",
      "KBC",
      "KBC Brussels",
      "Keytrade Bank",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Nagelmackers",
      "Neteller",
      "Nickel Beta",
      "PayPal",
      "Paysera",
      "Qonto",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Sumitomo Mitsui Banking Corporation",
      "Swan",
      "Triodos Bank",
      "VDK Bank",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "BG",
    "name": "Bulgaria",
    "slug": "bulgaria",
    "bankCount": 24,
    "banks": [
      "Airwallex",
      "bunq",
      "Central Cooperative Bank",
      "DSK Bank",
      "Fibank",
      "Finom",
      "HSBCnet",
      "ING Wholesale Banking",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Postbank",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Unicredit Bulbank",
      "United Bulgarian Bank",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "HR",
    "name": "Croatia",
    "slug": "croatia",
    "bankCount": 32,
    "banks": [
      "Addiko Bank",
      "Agram Banka",
      "Airwallex",
      "BKS Bank",
      "bunq",
      "Erste&Steiermärkische Bank d.d.",
      "Finom",
      "Hrvatska poštanska banka",
      "HSBCnet",
      "Istarska Kreditna Banka",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "OTP banka",
      "PayPal",
      "Paysera",
      "Podravska Banka",
      "Privredna banka Zagreb",
      "Raiffeisen Bank",
      "Raiffeisen Bank Corporate",
      "Revolut",
      "Skrill",
      "Slatinska Banka",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise",
      "Zagrebačka banka Corporate",
      "Zagrebačka banka Retail",
      "Zagrebačka banka UC eBanking Global"
    ]
  },
  {
    "code": "CY",
    "name": "Cyprus",
    "slug": "cyprus",
    "bankCount": 20,
    "banks": [
      "Airwallex",
      "AstroBank",
      "Bank of Cyprus",
      "bunq",
      "Eurobank Limited",
      "Finom",
      "HSBCnet",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "CZ",
    "name": "Czechia",
    "slug": "czech-republic",
    "bankCount": 31,
    "banks": [
      "Air Bank",
      "Airwallex",
      "Banka Creditas",
      "bunq",
      "Česká spořitelna",
      "Československá obchodní banka",
      "Commerzbank",
      "Finom",
      "Fio banka",
      "HSBCnet",
      "ING Wholesale Banking",
      "Komerční banka",
      "Lunar",
      "mBank Retail",
      "Monese",
      "Moneta Money Bank",
      "N26 Bank",
      "Neteller",
      "Oberbank",
      "PayPal",
      "Paysera",
      "PPF Banka",
      "Raiffeisen Bank",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Unicredit",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "DK",
    "name": "Denmark",
    "slug": "denmark",
    "bankCount": 91,
    "banks": [
      "Airwallex",
      "Andelskassen Fælleskassen",
      "Arbejdernes Landsbank",
      "Bank Norwegian",
      "BankNordik Denmark",
      "Borbjerg Sparekasse",
      "bunq",
      "Circle K Mastercard",
      "Coop Bank",
      "Danske Andelskassers Bank",
      "Danske Bank Business",
      "Danske Bank Private",
      "Djurslands Bank",
      "Djurslands Bank Corporate",
      "Dragsholm Sparekasse",
      "Entercard",
      "Eurocard",
      "Eurocard Corporate",
      "Facit bank",
      "Fanø Sparekasse",
      "Faster Andelskasse",
      "Finom",
      "Forbrugsforeningen",
      "Frørup Andelskasse",
      "Frøslev - Mollerup Sparekasse",
      "Fynske Bank",
      "GlobeCard",
      "HSBCnet",
      "Hvidbjerg Bank",
      "Ikano Bank",
      "Jyske Bank",
      "Jyske Bank Corporate",
      "Jyske Visa",
      "Jyske Visa Corporate",
      "Klim Sparekasse",
      "Kreditbanken",
      "Kreditbanken Corporate",
      "Lægernes Bank",
      "Lån & Spar Bank AS",
      "Lollands Bank",
      "Lunar",
      "Maj Bank",
      "Merkur Andelskasse",
      "Middelfart Sparekasse",
      "Monese",
      "Møns Bank",
      "N26 Bank",
      "Neteller",
      "Nordea Business",
      "Nordea Corporate",
      "Nordea Personal",
      "Nordfyns Bank",
      "Nordfyns Bank Corporate",
      "Nykredit",
      "PayPal",
      "Paysera",
      "PenSam Bank",
      "Pleo",
      "Resurs Bank",
      "Revolut",
      "Ringkjøbing Landbobank",
      "Ringkjøbing Landbobank Corporate",
      "Rise Sparekasse",
      "Rønde Sparekasse",
      "SAS Mastercard",
      "SEB",
      "SEB Kort Bank AB",
      "SEB Kort Bank AB Corporate",
      "Skjern Bank",
      "Skjern Bank Corporate",
      "Skrill",
      "Soldo",
      "Sønderhå-Hørsted Sparekasse",
      "Spar Nord Bank",
      "Sparekassen Balling",
      "Sparekassen Bredebro",
      "Sparekassen Danmark",
      "Sparekassen for Nørre Nebel",
      "Sparekassen Kronjylland",
      "Sparekassen Sjælland-Fyn",
      "Sparekassen Sjælland-Fyn Corporate",
      "Sparekassen Thy",
      "Stadil Sparekasse",
      "Stripe",
      "Swan",
      "Sydbank",
      "Sydbank Corporate",
      "Sydjysk Sparekasse",
      "Vestjysk Bank",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "EE",
    "name": "Estonia",
    "slug": "estonia",
    "bankCount": 24,
    "banks": [
      "Airwallex",
      "bunq",
      "Citadele",
      "Coop Pank",
      "Finom",
      "HSBCnet",
      "LHV",
      "Luminor",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "OP Corporate Bank",
      "PayPal",
      "Paysera",
      "Revolut",
      "SEB",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Swedbank",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "FI",
    "name": "Finland",
    "slug": "finland",
    "bankCount": 43,
    "banks": [
      "Airwallex",
      "Aktia",
      "Ålandsbanken",
      "Bank Norwegian",
      "bunq",
      "Danske Bank Business",
      "Danske Bank Private",
      "Eurocard",
      "Eurocard Corporate",
      "Finnair Mastercard",
      "Finom",
      "Handelsbanken Corporate",
      "Handelsbanken Private",
      "Holvi",
      "HSBCnet",
      "Ikano Bank",
      "Lunar",
      "Monese",
      "Morrow Bank",
      "N26 Bank",
      "Neteller",
      "Nordea Business",
      "Nordea Corporate",
      "Nordea Personal",
      "Oma Säästöpankki",
      "OP Financial Group",
      "Opel Mastercard Corporate",
      "PayPal",
      "Paysera",
      "POP Pankki",
      "Resurs Bank",
      "Revolut",
      "S-Pankki",
      "Säästöpankki",
      "SAS Mastercard",
      "SEB Kort Bank AB",
      "SEB Kort Bank AB Corporate",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "FR",
    "name": "France",
    "slug": "france",
    "bankCount": 138,
    "banks": [
      "Airwallex",
      "Allianz Banque",
      "American Express",
      "Arkéa Banking Services",
      "Arkéa Banque Entreprises et Institutionnels",
      "Arkéa Banque Privée",
      "Axa Banque",
      "Banque BCP",
      "Banque Chalus",
      "Banque de Savoie",
      "Banque Europeenne Credit Mutuel",
      "Banque Palatine",
      "Banque Populaire Alsace Lorraine Champagne",
      "Banque Populaire Aquitaine Centre Atlantique",
      "Banque Populaire Auvergne et Rhône-Alpes",
      "Banque Populaire Bourgogne Franche Comté",
      "Banque Populaire du Nord",
      "Banque Populaire du Sud",
      "Banque Populaire Grand Ouest",
      "Banque Populaire Méditerranée",
      "Banque Populaire Occitane",
      "Banque Populaire Rives de Paris",
      "Banque Populaire Val de France",
      "Banque Transatlantique",
      "BforBank",
      "BNP Paribas",
      "BNP Paribas Antilles-Guyane",
      "BNP Paribas Entreprise",
      "BNP Paribas Nouvelle Calédonie",
      "BNP Paribas Réunion",
      "BoursoBank",
      "BRED Banque Populaire",
      "BTP Banque",
      "bunq",
      "Caisse d'Epargne Aquitaine Poitou-Charentes",
      "Caisse d'Epargne Auvergne et Limousin",
      "Caisse d'Epargne Bourgogne Franche-Comté",
      "Caisse d'Epargne Bretagne-Pays De Loire",
      "Caisse d'Epargne Côte d'Azur",
      "Caisse d'Epargne Grand Est Europe",
      "Caisse d'Epargne Hauts de France",
      "Caisse d'Epargne Ile De France",
      "Caisse d'Epargne Languedoc-Roussillon",
      "Caisse d'Epargne Loire Drôme Ardèche",
      "Caisse d'Epargne Loire-Centre",
      "Caisse d'Epargne Midi-Pyrénées",
      "Caisse d'Epargne Normandie",
      "Caisse d'Epargne Provence Alpes Corse",
      "Caisse d'Epargne Rhône Alpes",
      "Caixa Geral De Depositos",
      "CIC Banque Privée",
      "Crédit Agricole Alpes Provence",
      "Crédit Agricole Alsace Vosges",
      "Crédit Agricole Atlantique Vendée",
      "Crédit Agricole Brie Picardie",
      "Crédit Agricole Champagne-Bourgogne",
      "Crédit Agricole Charente Périgord",
      "Crédit Agricole Charente-Maritime Deux-Sèvres",
      "Crédit Agricole d'Aquitaine",
      "Crédit Agricole d'Ille et Vilaine",
      "Crédit Agricole de Centre France",
      "Crédit Agricole de Centre Loire",
      "Crédit Agricole de Centre-Est",
      "Crédit Agricole de Franche-Comté",
      "Crédit Agricole de Guadeloupe",
      "Crédit Agricole de l'Anjou et du Maine",
      "Crédit Agricole de la Corse",
      "Crédit Agricole de la Martinique et de la Guyane",
      "Crédit Agricole de la Réunion",
      "Crédit Agricole de la Touraine et du Poitou",
      "Crédit Agricole de Loire Haute-Loire",
      "Crédit Agricole de Lorraine",
      "Crédit Agricole de Nord De France",
      "Crédit Agricole de Normandie",
      "Crédit Agricole de Normandie Seine",
      "Crédit Agricole de Paris et d'Ile de France",
      "Crédit Agricole de Provence Côtes d'Azur",
      "Crédit Agricole des Côtes d'Armor",
      "Crédit Agricole des Savoie",
      "Crédit Agricole du Centre Ouest",
      "Crédit Agricole du Finistère",
      "Crédit Agricole du Languedoc",
      "Crédit Agricole du Morbihan",
      "Crédit Agricole du Nord Est",
      "Crédit Agricole Nord Midi-Pyrénées",
      "Crédit Agricole Pyrénées Gascogne",
      "Crédit Agricole Sud Méditerranée",
      "Crédit Agricole Sud Rhône-Alpes",
      "Crédit Agricole Toulouse31",
      "Crédit Agricole Val De France",
      "Crédit Coopératif",
      "Crédit Industriel et Commercial (CIC)",
      "Crédit Maritime Mutuel Grand Ouest",
      "Crédit Maritime Mutuel Littoral du Sud Ouest",
      "Credit Municipal",
      "Crédit Mutuel",
      "Crédit Mutuel de Bretagne",
      "Crédit Mutuel du Sud-Ouest",
      "Ebury",
      "Finom",
      "Fortuneo Banque",
      "Hello bank!",
      "HSBCnet",
      "ING Wholesale Banking",
      "KBC",
      "La Banque Postale",
      "Lazard Freres Banque",
      "LCL",
      "LCL Corporate",
      "Louvre Banque Privée",
      "Lunar",
      "Manager One",
      "Memo Bank",
      "Milleis Banque",
      "Monabanq",
      "Monese",
      "N26 Bank",
      "Neteller",
      "Neuflize OBC",
      "Nickel Beta",
      "PayPal",
      "Paysera",
      "Qonto",
      "Revolut",
      "Shine",
      "Skrill",
      "Société Générale",
      "Société Générale Medium Enterprise",
      "Société Générale Small Enterprise",
      "Soldo",
      "Stripe",
      "Sumitomo Mitsui Banking Corporation",
      "Swan",
      "UBS",
      "Union Bancaire Privée",
      "Union Bancaire Privée des Moulins",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "DE",
    "name": "Germany",
    "slug": "germany",
    "bankCount": 1104,
    "banks": [
      "1822direkt",
      "Aachener Bank",
      "Aareal Bank AG",
      "ABN AMRO Bank Commercial",
      "Abtsgmünder Bank",
      "Airbus Bank",
      "Airwallex",
      "Aktivbank",
      "Alxing-Brucker Genossenschaftsbank",
      "apoBank",
      "Bank für Kirche und Diakonie - KD-Bank",
      "Bank für Sozialwirtschaft AG",
      "Bank im Bistum Essen",
      "Bank Norwegian",
      "Bank Saar",
      "Bank11 für Privatkunden und Handel",
      "Bankhaus Anton Hafner",
      "Bankhaus Bauer Aktiengesellschaft",
      "Bankhaus E Mayer",
      "Bankhaus Ellwanger & Geiger",
      "Bankhaus Gebr. Martin",
      "Bankhaus J. Faisst",
      "Bankhaus Lampe",
      "Bankhaus Max Flessa KG",
      "Bankhaus Rautenschlein",
      "Bankhaus Werhahn",
      "Bankhaus Werhahn",
      "BBBank",
      "Bensberger Bank",
      "Berenberg Bank",
      "Berliner Sparkasse",
      "Berliner Volksbank Abteilung BIT",
      "Bernhauser Bank",
      "Bethmann Bank",
      "BfW - Bank für Wohnungswirtschaft AG",
      "BNP Paribas",
      "Bopfinger Bank Sechta-Ries",
      "Bordesholmer Sparkasse AG",
      "Brandenburger Bank Volksbank-Raiffeisenbank",
      "Bremische Volksbank",
      "Brühler Bank",
      "BTV Bank",
      "BTV Bank für Tirol und Vorarlberg Zweigniederlassung Deutschland",
      "Budenheimer Volksbank",
      "bunq",
      "C24",
      "Comdirect",
      "Commerzbank",
      "Connexis Cash",
      "Consors Finanz",
      "Consorsbank",
      "Cronbank",
      "CVW-Privatbank",
      "DAB BNP Paribas",
      "Degussa Bank",
      "Dettinger Bank",
      "Deutsche Bank",
      "Deutsche Bundesbank",
      "Deutsche Kreditbank AG (DKB)",
      "Dithmarscher Volks- und Raiffeisenbank",
      "DKM Darlehnskasse Münster",
      "Donau-Iller Bank",
      "Donner Reuschel",
      "Dortmunder Volksbank",
      "DZ BANK AG Deutsche Zentral-Genossenschaftsbank",
      "Ebury",
      "Echterdinger Bank",
      "Eckernförder Bank Volksbank-Raiffeisenbank",
      "EDEKABANK Hamburg",
      "Emsländische Volksbank eG",
      "Erzgebirgssparkasse",
      "EthikBank",
      "Eurocity Bank",
      "Europäisch-Iranische Handelsbank",
      "Evangelische Bank",
      "Evenord-Bank",
      "Finom",
      "flatexDEGIRO Bank AG",
      "FNZ Bank",
      "Förde Sparkasse",
      "Frankfurter Bankgesellschaft",
      "Frankfurter Sparkasse",
      "Frankfurter Volksbank",
      "Freisinger Bank Volksbank-Raiffeisenbank",
      "Fürst Fugger Privatbank Aktiengesellschaft",
      "Fürstlich Castell'sche Bank Credit-Casse",
      "Gabler-Saliter Bankgeschäft",
      "GENO BANK ESSEN",
      "Genossenschaftsbank München",
      "Genossenschaftsbank Unterallgäu",
      "Genossenschaftsbank Weil im Schönbuch",
      "Gladbacher Bank",
      "GLS Gemeinschaftsbank",
      "Grafschafter Volksbank",
      "GRENKE BANK",
      "Hagnauer Volksbank",
      "Hamburger Sparkasse",
      "Hamburger Volksbank",
      "Hannoversche Volksbank",
      "Harzer Volksbank",
      "Harzsparkasse",
      "Hausbank",
      "Heidenheimer Volksbank",
      "Hoerner Bank",
      "HSBC Trinkaus & Burkhardt",
      "HSBCnet",
      "Hümmlinger Volksbank",
      "Hüttenberger Bank",
      "HypoVereinsbank",
      "HypoVereinsbank UC eBanking Global",
      "IBM Deutschland Kreditbank",
      "Ikano Bank",
      "ING",
      "ING Wholesale Banking",
      "Internationales Bankhaus Bodensee",
      "Isbank",
      "J&T BANKA",
      "Kasseler Sparkasse",
      "Kieler Volksbank",
      "Klarna Bank AB",
      "Kontist",
      "Kreis- und Stadtsparkasse Wasserburg",
      "Kreissparkasse Ahrweiler",
      "Kreissparkasse Anhalt-Bitterfeld",
      "Kreissparkasse Bautzen",
      "Kreissparkasse Bersenbrück",
      "Kreissparkasse Biberach",
      "Kreissparkasse Birkenfeld",
      "Kreissparkasse Bitburg-Prüm",
      "Kreissparkasse Böblingen",
      "Kreissparkasse Börde",
      "Kreissparkasse Döbeln ",
      "Kreissparkasse Düsseldorf",
      "Kreissparkasse Eichsfeld",
      "Kreissparkasse Esslingen-Nürtingen",
      "Kreissparkasse Euskirchen",
      "Kreissparkasse Freudenstadt",
      "Kreissparkasse Gelnhausen",
      "Kreissparkasse Göppingen",
      "Kreissparkasse Gotha",
      "Kreissparkasse Groß-Gerau",
      "Kreissparkasse Heidenheim",
      "Kreissparkasse Heilbronn",
      "Kreissparkasse Heinsberg",
      "Kreissparkasse Herzogtum Lauenburg",
      "Kreissparkasse Hildburghausen",
      "Kreissparkasse Kaiserslautern",
      "Kreissparkasse Kelheim",
      "Kreissparkasse Köln",
      "Kreissparkasse Kusel",
      "Kreissparkasse Limburg",
      "Kreissparkasse Ludwigsburg",
      "Kreissparkasse Märkisch-Oderland",
      "Kreissparkasse Mayen",
      "Kreissparkasse Melle",
      "Kreissparkasse Miesbach-Tegernsee",
      "Kreissparkasse München Starnberg Ebersberg",
      "Kreissparkasse Nordhausen",
      "Kreissparkasse Nordhorn",
      "Kreissparkasse Northeim",
      "Kreissparkasse Ostalb",
      "Kreissparkasse Ravensburg",
      "Kreissparkasse Reutlingen",
      "Kreissparkasse Rhein-Hunsrück",
      "Kreissparkasse Rottweil",
      "Kreissparkasse Saale-Orla",
      "Kreissparkasse Saalfeld-Rudolstadt",
      "Kreissparkasse Saarlouis",
      "Kreissparkasse Saarpfalz",
      "Kreissparkasse Schlüchtern",
      "Kreissparkasse Schwalm-Eder",
      "Kreissparkasse Sigmaringen",
      "Kreissparkasse Soltau",
      "Kreissparkasse St. Wendel",
      "Kreissparkasse Stade",
      "Kreissparkasse Steinfurt",
      "Kreissparkasse Stendal",
      "Kreissparkasse Syke",
      "Kreissparkasse Traunstein-Trostberg",
      "Kreissparkasse Tübingen",
      "Kreissparkasse Tuttlingen",
      "Kreissparkasse Verden",
      "Kreissparkasse Vulkaneifel",
      "Kreissparkasse Waiblingen",
      "Kreissparkasse Walsrode",
      "Kreissparkasse Weilburg",
      "Kreissparkasse Wiedenbrück",
      "Kurhessische Landbank",
      "Kyffhäusersparkasse Artern-Sondershausen",
      "Landbank Horlofftal",
      "Landesbank Saar",
      "Landessparkasse Oldenburg",
      "LBBW",
      "Leipziger Volksbank",
      "levoBank",
      "LIGA Bank",
      "Lunar",
      "M. M. Warburg & CO Bank",
      "Märkische Bank",
      "meine Volksbank Raiffeisenbank",
      "Mendener Bank",
      "Merck Finck Privatbankiers",
      "MERKUR BANK",
      "Mittelbrandenburgische Sparkasse in Potsdam",
      "MKB Mittelstandskreditbank",
      "MLP Finanzdienstleistungen",
      "Monese",
      "MUFG Bank",
      "MUFG Bank Corporate",
      "Münchner Bank",
      "Müritz-Sparkasse",
      "N26 Bank",
      "Nassauische Sparkasse",
      "National-Bank",
      "Neteller",
      "Nickel Beta",
      "Niederrheinische Sparkasse RheinLippe",
      "Nord-Ostsee Sparkasse",
      "NORD/LB",
      "Norisbank",
      "Oberbank",
      "ODDO BHF-Bank",
      "Onstmettinger Bank",
      "Ostfriesische Volksbank",
      "Ostsächsische Sparkasse Dresden",
      "OstseeSparkasse Rostock",
      "Otto M Schröder Bank",
      "Pax-Bank Kirche und Caritas",
      "PayPal",
      "Paysera",
      "Pleo",
      "Postbank",
      "PSD Bank Braunschweig",
      "PSD Bank Hannover",
      "PSD Bank Hessen-Thüringen",
      "PSD Bank Karlsruhe-Neustadt",
      "PSD Bank Koblenz",
      "PSD Bank München",
      "PSD Bank Nord",
      "PSD Bank Nürnberg",
      "PSD Bank Rhein-Ruhr",
      "PSD Bank RheinNeckarSaar",
      "PSD Bank West",
      "Qonto",
      "Raiffeisen - meine Bank",
      "Raiffeisen Baiertal",
      "Raiffeisen SparKreditbank",
      "Raiffeisen-Bank Eschweiler",
      "Raiffeisen-Volksbank",
      "Raiffeisen-Volksbank Bad Staffelstein",
      "Raiffeisen-Volksbank Donauwörth",
      "Raiffeisen-Volksbank Ebersberg",
      "Raiffeisen-Volksbank Fresena",
      "Raiffeisen-Volksbank Haßberge",
      "Raiffeisen-Volksbank Hermsdorfer Kreuz",
      "Raiffeisen-Volksbank Neustadt",
      "Raiffeisen-Volksbank Oder-Spree",
      "Raiffeisen-Volksbank Ries",
      "Raiffeisen-Volksbank Tüssling-Unterneukirchen",
      "Raiffeisenbank Aichhalden-Hardt- Sulgen",
      "Raiffeisenbank Aidlingen",
      "Raiffeisenbank Aindling",
      "Raiffeisenbank Aitrang-Ruderatshofen",
      "Raiffeisenbank Alteglofsheim-Hagelstadt",
      "Raiffeisenbank Altmühl-Jura",
      "Raiffeisenbank Altschweier",
      "Raiffeisenbank am Kulm",
      "Raiffeisenbank Anger",
      "Raiffeisenbank Aresing-Gerolsbach",
      "Raiffeisenbank Arnstorf",
      "Raiffeisenbank Aschau-Samerberg",
      "Raiffeisenbank Auerbach-Freihung",
      "Raiffeisenbank Augsburger Land West",
      "Raiffeisenbank Bad Kötzting",
      "Raiffeisenbank Bad Saulgau",
      "Raiffeisenbank Bad Windsheim",
      "Raiffeisenbank Baisweil-Eggenthal-Friesenried",
      "Raiffeisenbank Baunatal",
      "Raiffeisenbank Bechhofen",
      "Raiffeisenbank Berghülen",
      "Raiffeisenbank Beuerberg-Eurasburg",
      "Raiffeisenbank Bidingen",
      "Raiffeisenbank Biebergrund-Petersberg",
      "Raiffeisenbank Bobingen",
      "Raiffeisenbank Böllingertal",
      "Raiffeisenbank Buch-Eching",
      "Raiffeisenbank Bühlertal",
      "Raiffeisenbank Burgebrach-Stegaurach",
      "Raiffeisenbank Bütthard-Gaukönigshofen",
      "Raiffeisenbank Chamer Land",
      "Raiffeisenbank Chiemgau-Nord-Obing",
      "Raiffeisenbank Deggendorf-Plattling-Sonnenwald",
      "Raiffeisenbank Denzlingen-Sexau",
      "Raiffeisenbank Dietersheim und Umgebung",
      "Raiffeisenbank Donau-Heuberg",
      "Raiffeisenbank DreiFranken",
      "Raiffeisenbank eG Rannungen",
      "Raiffeisenbank Eifel",
      "Raiffeisenbank Elbmarsch",
      "Raiffeisenbank Elsavatal",
      "Raiffeisenbank Elztal",
      "Raiffeisenbank Ems-Vechte",
      "Raiffeisenbank Erlenbach",
      "Raiffeisenbank Ersingen",
      "Raiffeisenbank Eschlkam-Lam-Lohberg-Neukirchen b.Hl.BLUT",
      "Raiffeisenbank Falkenstein-Wörth",
      "Raiffeisenbank Flachsmeer",
      "Raiffeisenbank Floß",
      "Raiffeisenbank Frankenhardt-Stimpfach",
      "Raiffeisenbank Fränkische Schweiz",
      "Raiffeisenbank Geiselhöring-Pfaffenberg",
      "Raiffeisenbank Geislingen-Rosenfeld",
      "Raiffeisenbank Gilching",
      "Raiffeisenbank Gmund am Tegernsee",
      "Raiffeisenbank Goldener Steig - Dreisessel",
      "Raiffeisenbank Grainet",
      "Raiffeisenbank Grävenwiesbach",
      "Raiffeisenbank Griesstätt-Halfing",
      "Raiffeisenbank Grimma",
      "Raiffeisenbank Gruibingen",
      "Raiffeisenbank Gymnich",
      "Raiffeisenbank Haag-Gars-Maitenbeth",
      "Raiffeisenbank Hallertau",
      "Raiffeisenbank Hardt-Bruhrain",
      "Raiffeisenbank Hengersberg-Schöllnach",
      "Raiffeisenbank Hersbruck",
      "Raiffeisenbank HessenNord",
      "Raiffeisenbank Hiltenfingen",
      "Raiffeisenbank Hirschau",
      "Raiffeisenbank Höchberg",
      "Raiffeisenbank Hochfranken West",
      "Raiffeisenbank Hohenloher Land",
      "Raiffeisenbank Holzkirchen-Otterfing",
      "Raiffeisenbank Ichenhausen",
      "Raiffeisenbank im Allgäuer Land",
      "Raiffeisenbank im Breisgau",
      "Raiffeisenbank im Donautal",
      "Raiffeisenbank im Fuldaer Land ",
      "Raiffeisenbank im Grabfeld",
      "Raiffeisenbank im Kreis Calw",
      "Raiffeisenbank im Landkreis Passau-Nord",
      "Raiffeisenbank im Oberland",
      "Raiffeisenbank im Oberpfälzer Jura",
      "Raiffeisenbank in Rheinhessen",
      "Raiffeisenbank Isar-Loisachtal",
      "Raiffeisenbank Kaarst",
      "Raiffeisenbank Kaiserstuhl",
      "Raiffeisenbank Kalbe-Bismark",
      "Raiffeisenbank Kastellaun",
      "Raiffeisenbank Kieselbronn",
      "Raiffeisenbank Kirchweihtal",
      "Raiffeisenbank Kirtorf",
      "Raiffeisenbank Knoblauchsland-Bibertgrund",
      "Raiffeisenbank Kreis Kelheim",
      "Raiffeisenbank Küps-Mitwitz-Stockheim",
      "Raiffeisenbank Landshuter Land",
      "Raiffeisenbank Lauenburg",
      "Raiffeisenbank Lechrain",
      "Raiffeisenbank Leezen",
      "Raiffeisenbank Lorup",
      "Raiffeisenbank Main-Spessart",
      "Raiffeisenbank Maitis",
      "Raiffeisenbank Mecklenburger Seenplatte",
      "Raiffeisenbank MEHR",
      "Raiffeisenbank Mehring-Leiwen",
      "Raiffeisenbank Mittelschwaben",
      "Raiffeisenbank Mittenwald",
      "Raiffeisenbank Moormerland",
      "Raiffeisenbank München-Nord",
      "Raiffeisenbank München-Süd",
      "Raiffeisenbank Nahe",
      "Raiffeisenbank Neumarkt i.d.OPf.",
      "Raiffeisenbank Neumarkt-St.Veit - Reischach",
      "Raiffeisenbank Neustadt",
      "Raiffeisenbank Niedere Alb",
      "Raiffeisenbank Niederwallmenach",
      "Raiffeisenbank Nördliche Bergstraße",
      "Raiffeisenbank Oberaudorf",
      "Raiffeisenbank Oberferrieden-Burgthann",
      "Raiffeisenbank Oberland",
      "Raiffeisenbank Oberpfalz NordWest",
      "Raiffeisenbank Oberpfalz Süd",
      "Raiffeisenbank Oberteuringen-Meckenbeuren",
      "Raiffeisenbank Ortenburg-Kirchberg",
      "Raiffeisenbank Ostprignitz - Ruppin",
      "Raiffeisenbank Ottenbach",
      "Raiffeisenbank Owschlag",
      "Raiffeisenbank Parkstetten",
      "Raiffeisenbank Pfaffenhausen",
      "Raiffeisenbank Pfaffenhofen adGlonn",
      "Raiffeisenbank Pfaffenwinkel",
      "Raiffeisenbank Plankstetten",
      "Raiffeisenbank Rastede",
      "Raiffeisenbank Rattiszell-Konzell",
      "Raiffeisenbank Regensburg-Wenzenbach",
      "Raiffeisenbank Regenstauf",
      "Raiffeisenbank Rehling",
      "Raiffeisenbank Reute-Gaisbeuren",
      "Raiffeisenbank Rodenbach",
      "Raiffeisenbank Rosenstein",
      "Raiffeisenbank RSA",
      "Raiffeisenbank Rupertiwinkel",
      "Raiffeisenbank Scharrel",
      "Raiffeisenbank Schrobenhausener Land",
      "Raiffeisenbank Schrozberg- Rot am See",
      "Raiffeisenbank Schwaben Mitte",
      "Raiffeisenbank Schwabmünchen-Stauden",
      "Raiffeisenbank Seestermühe",
      "Raiffeisenbank Singoldtal",
      "Raiffeisenbank Sinzing",
      "Raiffeisenbank Sondelfingen",
      "Raiffeisenbank Steingaden",
      "Raiffeisenbank Straubing",
      "Raiffeisenbank Strücklingen- Idafehn",
      "Raiffeisenbank Südhardt",
      "Raiffeisenbank Südliches Ostallgäu",
      "Raiffeisenbank Südstormarn Mölln",
      "Raiffeisenbank Taufkirchen-Oberneukirchen",
      "Raiffeisenbank Thannhausen",
      "Raiffeisenbank Todenbüttel",
      "Raiffeisenbank Tüngental",
      "Raiffeisenbank Türkheim",
      "Raiffeisenbank Ühlfeld-Dachsbach",
      "Raiffeisenbank Unteres Inntal",
      "Raiffeisenbank Unteres Vilstal",
      "Raiffeisenbank Unteres Zusamtal",
      "Raiffeisenbank Volkacher Mainschleife - Wiesentheid",
      "Raiffeisenbank Wald-Görisried",
      "Raiffeisenbank Wallgau-Krün",
      "Raiffeisenbank Wangen",
      "Raiffeisenbank Wegscheid",
      "Raiffeisenbank Welling",
      "Raiffeisenbank Werratal-Landeck",
      "Raiffeisenbank Wesermarsch-Süd",
      "Raiffeisenbank Westeifel",
      "Raiffeisenbank Westhausen",
      "Raiffeisenbank Westkreis Fürstenfeldbruck",
      "Raiffeisenbank Wiesedermeer- Wiesede-Marcardsmoor",
      "Raiffeisenbank Wittelsbacher Land",
      "Raiffeisenbank Wüstenselbitz",
      "Raiffeisenbank Wyhl",
      "Revolut",
      "Rheingauer Volksbank",
      "Rhön-Rennsteig Sparkasse ",
      "RSB RetailService Bank",
      "Saalesparkasse",
      "Salzlandsparkasse",
      "Schrobenhausener Bank",
      "Skrill",
      "Soldo",
      "Spar- und Darlehnskasse Bockum-Hövel",
      "Spar- und Darlehnskasse Börde Lamstedt-Hechthausen",
      "Spar- und Kreditbank Bühlertal",
      "Spar- und Kreditbank des Bundes Freier evangelischer Gemeinden",
      "Spar- und Kreditbank Evangelisch-Freikirchlicher Gemeinden",
      "Spar- und Kreditbank Hammah",
      "Spar- und Kreditbank Rheinstetten",
      "Spar-u. Kredit-Bank",
      "Sparda Bank Augsburg eG",
      "Sparda Bank West Düsseldorf",
      "Sparda Bank West Münster",
      "Sparda Bank West Wuppertal",
      "Sparda-Bank Baden-Württemberg eG",
      "Sparda-Bank Berlin eG",
      "Sparda-Bank Hamburg eG",
      "Sparda-Bank Hannover eG",
      "Sparda-Bank Hessen eG",
      "Sparda-Bank München eG",
      "Sparda-Bank Nürnberg eG",
      "Sparda-Bank Ostbayern eG",
      "Sparda-Bank Südwest eG",
      "Sparkasse Aachen",
      "Sparkasse Aichach-Schrobenhausen",
      "Sparkasse Allgäu",
      "Sparkasse Altenburger Land",
      "Sparkasse Altmark West",
      "Sparkasse Altötting-Mühldorf",
      "Sparkasse am Niederrhein",
      "Sparkasse Amberg-Sulzbach",
      "Sparkasse an der Lippe",
      "Sparkasse Ansbach",
      "Sparkasse Arnsberg-Sundern",
      "Sparkasse Arnstadt-Ilmenau",
      "Sparkasse Aschaffenburg-Alzenau",
      "Sparkasse Attendorn-Lennestadt-Kirchhundem",
      "Sparkasse Aurich-Norden",
      "Sparkasse Bad Hersfeld-Rotenburg",
      "Sparkasse Bad Kissingen",
      "Sparkasse Bad Neustadt a.d. Saale",
      "Sparkasse Bad Oeynhausen - Porta Westfalica",
      "Sparkasse Bad Tölz-Wolfratshausen",
      "Sparkasse Baden-Baden Gaggenau",
      "Sparkasse Bamberg",
      "Sparkasse Barnim",
      "Sparkasse Battenberg",
      "Sparkasse Bayreuth",
      "Sparkasse Bensheim",
      "Sparkasse Berchtesgadener Land",
      "Sparkasse Bergkamen-Bönen",
      "Sparkasse Bielefeld",
      "Sparkasse Bochum",
      "Sparkasse Bodensee",
      "Sparkasse Bonndorf-Stühlingen",
      "Sparkasse Bottrop",
      "Sparkasse Bremen",
      "Sparkasse Bühl",
      "Sparkasse Burbach-Neunkirchen",
      "Sparkasse Burgenlandkreis",
      "Sparkasse Celle-Gifhorn-Wolfsburg",
      "Sparkasse Chemnitz",
      "Sparkasse Coburg-Lichtenfels",
      "Sparkasse Dachau",
      "Sparkasse Darmstadt",
      "Sparkasse Deggendorf",
      "Sparkasse Dieburg",
      "Sparkasse Dillenburg",
      "Sparkasse Dillingen-Nördlingen",
      "Sparkasse Donauwörth",
      "Sparkasse Donnersberg",
      "Sparkasse Dortmund",
      "Sparkasse Duderstadt",
      "Sparkasse Duisburg",
      "Sparkasse Düren",
      "Sparkasse Einbeck",
      "Sparkasse Elbe-Elster",
      "Sparkasse Elmshorn",
      "Sparkasse Emden",
      "Sparkasse Emsland",
      "Sparkasse Engen-Gottmadingen",
      "Sparkasse Erding-Dorfen",
      "Sparkasse Erlangen Höchstadt Herzogenaurach",
      "Sparkasse Eschenbach Neustadt (a.d. Waldnaab)",
      "Sparkasse Essen",
      "Sparkasse Forchheim",
      "Sparkasse Freiburg-Nördlicher Breisgau ",
      "Sparkasse Freising",
      "Sparkasse Freyung-Grafenau",
      "Sparkasse Fulda",
      "Sparkasse Fürstenfeldbruck",
      "Sparkasse Fürth",
      "Sparkasse Gelsenkirchen",
      "Sparkasse Gera-Greiz",
      "Sparkasse Geseke",
      "Sparkasse Gevelsberg-Wetter",
      "Sparkasse Gießen",
      "Sparkasse Gladbeck",
      "Sparkasse Göttingen",
      "Sparkasse Grünberg",
      "Sparkasse Gummersbach",
      "Sparkasse Gunzenhausen",
      "Sparkasse Gütersloh-Rietberg",
      "Sparkasse HagenHerdecke",
      "Sparkasse Hameln-Weserbergland",
      "Sparkasse Hamm",
      "Sparkasse Hanau",
      "Sparkasse Hanauerland",
      "Sparkasse Hannover",
      "Sparkasse Harburg-Buxtehude",
      "Sparkasse Haslach-Zell",
      "Sparkasse Hattingen",
      "Sparkasse Hegau-Bodensee",
      "Sparkasse Heidelberg",
      "Sparkasse Herford",
      "Sparkasse Herne",
      "Sparkasse Hilden-Ratingen-Velbert",
      "Sparkasse Hildesheim Goslar Peine",
      "Sparkasse Hochfranken",
      "Sparkasse Hochrhein",
      "Sparkasse Hochsauerland",
      "Sparkasse Hochschwarzwald",
      "Sparkasse Hohenlohekreis",
      "Sparkasse Holstein",
      "Sparkasse im Landkreis Cham",
      "Sparkasse im Landkreis Cham Iserlohn",
      "Sparkasse im Landkreis Schwandorf",
      "Sparkasse IngolstadtEichstätt",
      "Sparkasse Jena-Saale-Holzland",
      "Sparkasse Karlsruhe ",
      "Sparkasse Kierspe-Meinerzhagen",
      "Sparkasse Koblenz ",
      "Sparkasse KölnBonn",
      "Sparkasse Kraichgau",
      "Sparkasse Krefeld",
      "Sparkasse Kulmbach-Kronach",
      "Sparkasse Landsberg-Dießen",
      "Sparkasse Landshut",
      "Sparkasse Langen-Seligenstadt",
      "Sparkasse Laubach-Hungen",
      "Sparkasse LeerWittmund",
      "Sparkasse Lemgo",
      "Sparkasse Leverkusen",
      "Sparkasse Lörrach-Rheinfelden",
      "Sparkasse Lüneburg",
      "Sparkasse Mainfranken Würzburg",
      "Sparkasse Mansfeld-Südharz",
      "Sparkasse Marburg-Biedenkopf",
      "Sparkasse Markgräflerland",
      "Sparkasse Märkisches Sauerland Hemer - Menden",
      "Sparkasse Mecklenburg-Nordwest",
      "Sparkasse Mecklenburg-Schwerin",
      "Sparkasse Mecklenburg-Strelitz",
      "Sparkasse Meißen",
      "Sparkasse Memmingen-Lindau-Mindelheim",
      "Sparkasse Merzig-Wadern",
      "Sparkasse Minden-Lübbecke",
      "Sparkasse Mittelfranken-Süd",
      "Sparkasse Mittelholstein AG",
      "Sparkasse Mittelmosel-Eifel-Mosel-Hunsrück",
      "Sparkasse Mittelsachsen",
      "Sparkasse Mittelthüringen",
      "Sparkasse Muldental ",
      "Sparkasse Mülheim a.d. Ruhr",
      "Sparkasse Münsterland-Ost",
      "Sparkasse Neckartal-Odenwald ",
      "Sparkasse Neu-Ulm-Illertissen",
      "Sparkasse Neubrandenburg-Demmin",
      "Sparkasse Neuburg-Rain",
      "Sparkasse Neumarkt i.d.OPf.-Parsberg ",
      "Sparkasse Neunkirchen",
      "Sparkasse Neuss",
      "Sparkasse Neustadt a.d. Aisch-Bad Windsheim",
      "Sparkasse Neuwied",
      "Sparkasse Niederbayern-Mitte",
      "Sparkasse Niederlausitz",
      "Sparkasse Nienburg",
      "Sparkasse Nürnberg",
      "Sparkasse Oberhessen",
      "Sparkasse Oberland",
      "Sparkasse Oberlausitz-Niederschlesien",
      "Sparkasse Oberpfalz Nord",
      "Sparkasse Odenwaldkreis",
      "Sparkasse Oder-Spree",
      "Sparkasse Offenburg/Ortenau",
      "Sparkasse Olpe-Drolshagen-Wenden",
      "Sparkasse Osnabrück",
      "Sparkasse Osterode am Harz",
      "Sparkasse Ostprignitz-Ruppin",
      "Sparkasse Paderborn-Detmold",
      "Sparkasse Passau",
      "Sparkasse Pfaffenhofen",
      "Sparkasse Pforzheim Calw",
      "Sparkasse Pfullendorf-Meßkirch",
      "Sparkasse Prignitz",
      "Sparkasse Rastatt-Gernsbach",
      "Sparkasse Regen-Viechtach",
      "Sparkasse Regensburg",
      "Sparkasse Rhein Neckar Nord",
      "Sparkasse Rhein-Haardt",
      "Sparkasse Rhein-Maas",
      "Sparkasse Rhein-Nahe",
      "Sparkasse Rosenheim-Bad Aibling",
      "Sparkasse Rotenburg Osterholz",
      "Sparkasse Rottal-Inn",
      "Sparkasse Saarbrücken",
      "Sparkasse Salem-Heiligenberg",
      "Sparkasse Schaumburg",
      "Sparkasse Scheeßel",
      "Sparkasse Schwäbisch Hall-Crailsheim",
      "Sparkasse Schwarzwald-Baar",
      "Sparkasse Schweinfurt-Haßberge",
      "Sparkasse Siegen",
      "Sparkasse SoestWerl",
      "Sparkasse Sonneberg",
      "Sparkasse Spree-Neiße",
      "Sparkasse St.Blasien",
      "Sparkasse Stade-Altes Land",
      "Sparkasse Starkenburg",
      "Sparkasse Staufen-Breisach",
      "Sparkasse Südholstein",
      "Sparkasse Südpfalz",
      "Sparkasse Suedwestpfalz",
      "Sparkasse Tauberfranken",
      "Sparkasse Trier",
      "Sparkasse Uckermark",
      "Sparkasse Uecker-Randow ",
      "Sparkasse Uelzen Lüchow-Dannenberg",
      "Sparkasse Ulm",
      "Sparkasse UnnaKamen",
      "Sparkasse Unstrut-Hainich",
      "Sparkasse Vest Recklinghausen",
      "Sparkasse Vogtland",
      "Sparkasse Vorderpfalz",
      "Sparkasse Vorpommern",
      "Sparkasse Waldeck-Frankenberg",
      "Sparkasse Werra-Meißner",
      "Sparkasse Westerwald-Sieg",
      "Sparkasse Westholstein",
      "Sparkasse Westmünsterland",
      "Sparkasse Wetzlar",
      "Sparkasse Wiesental",
      "Sparkasse Wilhelmshaven",
      "Sparkasse Witten",
      "Sparkasse Wittenberg",
      "Sparkasse Wittgenstein",
      "Sparkasse Wolfach",
      "Sparkasse Worms-Alzey-Ried",
      "Sparkasse Zollernalb",
      "Sparkasse zu Lübeck AG",
      "Sparkasse Zwickau",
      "Spreewaldbank",
      "St. Galler Kantonalbank",
      "Stadt- und Kreissparkasse Leipzig ",
      "Stadtsparkasse Augsburg",
      "Stadtsparkasse Bad Pyrmont",
      "Stadtsparkasse Barsinghausen",
      "Stadtsparkasse Bocholt",
      "Stadtsparkasse Burgdorf",
      "Stadtsparkasse Cuxhaven",
      "Stadtsparkasse Dessau",
      "Stadtsparkasse Düsseldorf",
      "Stadtsparkasse Grebenstein",
      "Stadtsparkasse Haan (Rheinland)",
      "Stadtsparkasse Langenfeld (Rheinland)",
      "Stadtsparkasse Lengerich ",
      "Stadtsparkasse Magdeburg",
      "Stadtsparkasse Mönchengladbach",
      "Stadtsparkasse München",
      "Stadtsparkasse Oberhausen",
      "Stadtsparkasse Offenbach",
      "Stadtsparkasse Rahden",
      "Stadtsparkasse Remscheid",
      "Stadtsparkasse Rheine",
      "Stadtsparkasse Schwalmstadt",
      "Stadtsparkasse Schwedt",
      "Stadtsparkasse Schwelm",
      "Stadtsparkasse Solingen",
      "Stadtsparkasse Wedel",
      "Stadtsparkasse Wermelskirchen",
      "Stadtsparkasse Wuppertal",
      "Steyler Bank",
      "Stripe",
      "Südtiroler Sparkasse Niederlassung München",
      "Südwestbank",
      "Sumitomo Mitsui Banking Corporation",
      "Swan",
      "Sydbank",
      "Sylter Bank",
      "Targobank",
      "Taunus Sparkasse",
      "Tomorrow",
      "Triodos Bank",
      "UBS",
      "UmweltBank",
      "UNION-BANK",
      "VakifBank International",
      "VBU Volksbank im Unterland",
      "VerbundVolksbank OWL",
      "Vereinigte Raiffeisenbank Burgstädt",
      "Vereinigte Sparkasse im Märkischen Kreis",
      "Vereinigte Volksbank Brakel",
      "Vereinigte Volksbank Ganderkesee-Hude-Bookholzberg- Lemwerder",
      "Vereinigte Volksbank Raiffeisenbank",
      "Vereinigte Volksbank Raiffeisenbank Reinheim ",
      "Vereinigte Volksbank Saarlouis - Losheim am See - SulzbachSaar",
      "Vereinigte Volksbanken Sindelfingen",
      "Vereinigte VR Bank Kur- und Rheinpfalz",
      "Vereinigte VR Bank Wyk auf Föhr",
      "Vereinte Volksbank",
      "Vietin Bank",
      "Vivid Money",
      "Volks- und Raiffeisenbank",
      "Volks- und Raiffeisenbank Fürstenwalde Seelow-Wriezen",
      "Volks- und Raiffeisenbank Muldental",
      "Volks- und Raiffeisenbank Prignitz",
      "Volks- und Raiffeisenbank Saale-Unstrut",
      "Volksbank - Die Gestalterbank",
      "Volksbank Adelebsen",
      "Volksbank Alb",
      "Volksbank Albstadt",
      "Volksbank Allgäu-Oberschwaben",
      "Volksbank Alzey-Worms",
      "Volksbank am Württemberg",
      "Volksbank an der Niers",
      "Volksbank Anröchte",
      "Volksbank Ascheberg-Herbern",
      "Volksbank Backnang",
      "Volksbank Bad Laer-Borgloh-Hilter-Melle",
      "Volksbank Bad Salzuflen",
      "Volksbank Baumberge",
      "Volksbank Beckum-Lippstadt",
      "Volksbank Beilstein-Ilsfeld- Abstatt",
      "Volksbank Berg",
      "Volksbank Bocholt",
      "Volksbank Bochum Witten",
      "Volksbank Bodensee-Oberschwaben",
      "Volksbank Bönen",
      "Volksbank Börde-Bernburg",
      "Volksbank Börßum-Hornburg",
      "Volksbank Brandoberndorf",
      "Volksbank Braunlage",
      "Volksbank Braunschweig Wolfsburg",
      "Volksbank Breisgau Nord",
      "Volksbank Breisgau- Markgräflerland",
      "Volksbank Bremen-Nord",
      "Volksbank Bremerhaven-Cuxland",
      "Volksbank Brenztal",
      "Volksbank Bühl",
      "Volksbank Butzbach",
      "Volksbank Chemnitz",
      "Volksbank Daaden",
      "Volksbank Dammer Berge",
      "Volksbank Darmstadt - Südhessen",
      "Volksbank Darmstadt Mainz",
      "Volksbank Deisslingen",
      "Volksbank Delbrück-Rietberg",
      "Volksbank Delitzsch",
      "Volksbank Demmin",
      "Volksbank Dessau-Anhalt",
      "Volksbank Dettenhausen",
      "Volksbank Dreiländereck",
      "Volksbank Dresden-Bautzen",
      "Volksbank Dünnwald-Holweide",
      "Volksbank Düsseldorf Neuss",
      "Volksbank Düte-Ems",
      "Volksbank eG Lohne - Dinklage - Steinfeld - Mühlen",
      "Volksbank eG Neckar Odenwald Main Tauber",
      "Volksbank eG Oldenburg-Land Delmenhors",
      "Volksbank Eisenberg",
      "Volksbank Elsen-Wewer-Borchen",
      "Volksbank Emmerich-Rees",
      "Volksbank Emstal",
      "Volksbank Enniger-Ostenfelde-Westkirchen",
      "Volksbank Erft",
      "Volksbank Ermstal-Alb",
      "Volksbank Essen-Cappeln",
      "Volksbank Ettlingen",
      "Volksbank Euskirchen",
      "Volksbank Eutin Raiffeisenbank",
      "Volksbank Filder",
      "Volksbank Flein-Talheim",
      "Volksbank Franken",
      "Volksbank Fredenbeck ",
      "Volksbank Freiburg",
      "Volksbank Friesoythe",
      "Volksbank Gardelegen",
      "Volksbank Gebhardshain",
      "Volksbank Geest",
      "Volksbank Geeste-Nord",
      "Volksbank Gera Jena Rudolstadt",
      "Volksbank Gescher",
      "Volksbank Glan-Münchweiler",
      "Volksbank Göppingen",
      "Volksbank Grebenhain",
      "Volksbank Gronau-Ahaus",
      "Volksbank Halle Saale",
      "Volksbank HalleWestf",
      "Volksbank Hameln-Stadthagen",
      "Volksbank Hamm Sieg",
      "Volksbank Haselünne",
      "Volksbank Heiden",
      "Volksbank Heimbach",
      "Volksbank Heinsberg",
      "Volksbank Hellweg",
      "Volksbank Heuchelheim",
      "Volksbank Hildesheim-Lehrte-Pattensen",
      "Volksbank Hochrhein",
      "Volksbank Hohenlimburg",
      "Volksbank Hohenlohe",
      "Volksbank im Bergischen Land",
      "Volksbank im Harz",
      "Volksbank im Hochsauerland",
      "Volksbank im Kreis Freudenstadt",
      "Volksbank im Münsterland",
      "Volksbank im Rheinland eG",
      "Volksbank im Wesertal",
      "Volksbank Immenstadt",
      "Volksbank in der Hohen Mark",
      "Volksbank in der Region",
      "Volksbank in Ostwestfalen",
      "Volksbank in Schaumburg und Nienburg",
      "Volksbank in Südwestfalen",
      "Volksbank Jade-Weser eG",
      "Volksbank Jerichower Land",
      "Volksbank Kaiserslautern",
      "Volksbank Kassel Göttingen",
      "Volksbank Kempen-Grefrath",
      "Volksbank Kierspe",
      "Volksbank Kirnau-Krautheim",
      "Volksbank Klettgau-Wutöschingen",
      "Volksbank Kleverland",
      "Volksbank Köln Bonn",
      "Volksbank Köthen-Bitterfeld",
      "Volksbank Kraichgau",
      "Volksbank Krefeld",
      "Volksbank Kurpfalz ",
      "Volksbank Lahr",
      "Volksbank Langendernbach",
      "Volksbank Lastrup",
      "Volksbank Lauterecken",
      "Volksbank Leonberg-Strohgäu",
      "Volksbank Limbach",
      "Volksbank Lindenberg",
      "Volksbank Löbau-Zittau",
      "Volksbank Löningen",
      "Volksbank Lübeck",
      "Volksbank Lüneburger Heide",
      "Volksbank Magdeburg",
      "Volksbank Mainspitze",
      "Volksbank Marl-Recklinghausen",
      "Volksbank Mittelhessen",
      "Volksbank Mittlerer Neckar",
      "Volksbank Mittlerer Schwarzwald",
      "Volksbank Mittleres Erzgebirge",
      "Volksbank Mittweida",
      "Volksbank Möckmühl",
      "Volksbank Münsingen",
      "Volksbank Neckartal",
      "Volksbank Niedergrafschaft",
      "Volksbank Niederrhein",
      "Volksbank Nordharz",
      "Volksbank Nordhümmling",
      "Volksbank Nottuln",
      "Volksbank Ober-Mörlen",
      "Volksbank Oberberg",
      "Volksbank Ochtrup-Laer",
      "Volksbank Oldenburg",
      "Volksbank Olpe-Wenden-Drolshagen",
      "Volksbank Osnabrück",
      "Volksbank Osterholz-Scharmbeck",
      "Volksbank Ostlippe",
      "Volksbank Oyten",
      "Volksbank Pfullendorf",
      "Volksbank Pirna",
      "Volksbank Plochingen",
      "Volksbank PLUS",
      "Volksbank pur",
      "Volksbank Raesfeld und Erle",
      "Volksbank Raiffeisenbank AmmerGäu",
      "Volksbank Raiffeisenbank Bad Kissingen",
      "Volksbank Raiffeisenbank Bad Oldesloe ",
      "Volksbank Raiffeisenbank Bayern Mitte",
      "Volksbank Raiffeisenbank Dachau",
      "Volksbank Raiffeisenbank Fürstenfeldbruck",
      "Volksbank Raiffeisenbank Meißen Großenhain",
      "Volksbank Raiffeisenbank Niederschlesien",
      "Volksbank Raiffeisenbank Nordoberpfalz",
      "Volksbank Raiffeisenbank Oberbayern Südost",
      "Volksbank Raiffeisenbank Regensburg-Schwandorf",
      "Volksbank Raiffeisenbank Würzburg",
      "Volksbank Rathenow",
      "Volksbank Remseck",
      "Volksbank Rhede",
      "Volksbank Rhein-Erft-Köln",
      "Volksbank Rhein-Lahn-Limburg",
      "Volksbank Rhein-Lippe",
      "Volksbank Rhein-Nahe-Hunsrück",
      "Volksbank Rhein-Ruhr",
      "Volksbank RheinAhrEifel",
      "Volksbank Rheinböllen",
      "Volksbank Riesa",
      "Volksbank Rot",
      "Volksbank Rottweil",
      "Volksbank Ruhr Mitte",
      "Volksbank Sandhofen",
      "Volksbank Sangerhausen",
      "Volksbank Sauerland",
      "Volksbank Schermbeck",
      "Volksbank Schlangen",
      "Volksbank Schwanewede",
      "Volksbank Schwarzwald-Donau-Neckar",
      "Volksbank Seesen",
      "Volksbank Seligenstadt",
      "Volksbank Selm-Bork",
      "Volksbank Senden",
      "Volksbank Solling",
      "Volksbank Spree-Neiße",
      "Volksbank Sprockhövel",
      "Volksbank Stade-Cuxhaven",
      "Volksbank Staufen",
      "Volksbank Stendal",
      "Volksbank Störmede-Hörste",
      "Volksbank Stuttgart",
      "Volksbank Süd-Emsland",
      "Volksbank Südheide - Isenhagener Land - Altmark",
      "Volksbank Südkirchen-Capelle-Nordkirchen",
      "Volksbank Sulingen",
      "Volksbank Sulmtal",
      "Volksbank Thüringen Mitte",
      "Volksbank Trier Eifel",
      "Volksbank Trossingen",
      "Volksbank Überherrn",
      "Volksbank Überlingen",
      "Volksbank Uelzen-Salzwedel",
      "Volksbank Ulm-Biberach",
      "Volksbank Ulrichstein",
      "Volksbank Vechta",
      "Volksbank Versmold",
      "Volksbank Viersen",
      "Volksbank Visbek",
      "Volksbank Vogtland-Saale-Orla",
      "Volksbank Vorpommern",
      "Volksbank Weschnitztal",
      "Volksbank Westerstede",
      "Volksbank Westrhauderfehn",
      "Volksbank Wilhelmshaven",
      "Volksbank Winsener Marsch",
      "Volksbank Wißmar",
      "Volksbank Wittenberg",
      "Volksbank Wittgenstein",
      "Volksbank Wolfenbüttel",
      "Volksbank Worpswede",
      "Volksbank Zuffenhausen",
      "Volksbank Zwickau",
      "Volksbank-Raiffeisenbank Glauchau",
      "Volkswagen Financial Services Corporate",
      "Volkswagen Financial Services Private",
      "VR Bank Alsheim",
      "VR Bank Amberg-Sulzbach",
      "VR Bank Augsburg-Ostallgäu",
      "VR Bank Bad Orb-Gelnhausen",
      "VR Bank Bamberg-Forchheim",
      "VR Bank Bayreuth-Hof",
      "VR Bank Bergisch Gladbach-Leverkusen",
      "VR Bank Burglengenfeld",
      "VR Bank Donau-Oberschwaben",
      "VR Bank Dreieich-Offenbach",
      "VR Bank Fulda",
      "VR Bank Heilbronn Schwäbisch Hall eG",
      "VR Bank HessenLand",
      "VR Bank Ihre Heimatbank eG ",
      "VR Bank in Holstein",
      "VR Bank in Thüringen",
      "VR Bank Kempten-Oberallgäu",
      "VR Bank Kitzingen",
      "VR Bank Lahn-Dill",
      "VR Bank Lausitz",
      "VR Bank Main-Kinzig-Büdingen",
      "VR Bank Metropolregion Nürnberg ",
      "VR Bank Mittelhaardt",
      "VR Bank Mittlere Oberpfalz",
      "VR Bank Monheim am Rhein ",
      "VR Bank München Land",
      "VR Bank Neuburg-Rain",
      "VR Bank Niederbayern-Oberpfalz",
      "VR Bank Nord",
      "VR Bank Oberfranken Mitte",
      "VR Bank Ostholstein Nord - Plön",
      "VR Bank Rhein-Neckar",
      "VR Bank Ried-Überwald",
      "VR Bank Schwäbischer Wald",
      "VR Bank Starnberg-Herrsching-Landsberg",
      "VR Bank Südliche Weinstraße-Wasgau",
      "VR Bank Südpfalz",
      "VR Bank Weimar",
      "VR Bank Westküste",
      "VR GenoBank DonauWald",
      "VR PartnerBank Chattengau-Schwalm-Eder",
      "VR PLUS Altmark-Wendland",
      "VR SüdBank",
      "VR-Bank Alb-Blau-Donau",
      "VR-Bank Altenburger Land",
      "VR-Bank Bad Salzungen Schmalkalden",
      "VR-Bank Bonn Rhein-Sieg",
      "VR-Bank Coburg",
      "VR-Bank Donau-Mindel",
      "VR-Bank Ehningen-Nufringen",
      "VR-Bank Ellwangen",
      "VR-Bank Erding",
      "VR-Bank Feuchtwangen-Dinkelsbühl",
      "VR-Bank Fichtelgebirge- Frankenwald",
      "VR-Bank Fläming",
      "VR-Bank Freudenberg-Niederfischbach",
      "VR-Bank Handels- und Gewerbebank",
      "VR-Bank in Mittelbaden",
      "VR-Bank in Südniedersachsen",
      "VR-Bank in Südoldenburg",
      "VR-Bank Isar-Vils",
      "VR-Bank Ismaning Hallbergmoos Neufahrn",
      "VR-Bank Landau-Mengkofen",
      "VR-Bank Landsberg-Ammersee",
      "VR-Bank Landshut",
      "VR-Bank Lichtenfels-Ebern",
      "VR-Bank Ludwigsburg",
      "VR-Bank Main-Rhön",
      "VR-Bank Memmingen",
      "VR-Bank Mitte",
      "VR-Bank Mittelfranken West",
      "VR-Bank Mittelsachsen",
      "VR-Bank Neu-Ulm",
      "VR-Bank Nordeifel",
      "VR-Bank NordRhön",
      "VR-Bank Osnabrücker Nordland",
      "VR-Bank Ostalb",
      "VR-Bank Ostbayern-Mitte",
      "VR-Bank Passau",
      "VR-Bank Rottal-Inn",
      "VR-Bank Spangenberg-Morschen",
      "VR-Bank Südwestpfalz Pirmasens - Zweibrücken",
      "VR-Bank Taufkirchen-Dorfen",
      "VR-Bank Uckermark-Randow",
      "VR-Bank Vilshofen-Pocking",
      "VR-Bank Westmünsterland",
      "VR-Bank Würselen ",
      "VR-MainBank",
      "Waldeck-Frankenberger Bank",
      "Wartburg-Sparkasse",
      "Weberbank",
      "WEG Bank",
      "Weser-Elbe Sparkasse",
      "Westerwald Bank Volks- und Raiffeisenbank",
      "Wiesbadener Volksbank",
      "Winterbacher Bank",
      "Wise",
      "Ziraat Bank International"
    ]
  },
  {
    "code": "GR",
    "name": "Greece",
    "slug": "greece",
    "bankCount": 25,
    "banks": [
      "Airwallex",
      "Alpha Bank",
      "Attica Bank",
      "Bank of Epirus",
      "bunq",
      "Ebury",
      "Eurobank Ergasias",
      "Finom",
      "HSBCnet",
      "Lunar",
      "Monese",
      "N26 Bank",
      "National Bank of Greece",
      "Neteller",
      "Optima Bank",
      "PayPal",
      "Paysera",
      "Piraeus Bank",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "HU",
    "name": "Hungary",
    "slug": "hungary",
    "bankCount": 31,
    "banks": [
      "Airwallex",
      "bunq",
      "CIB Bank",
      "CIB Bank Business",
      "Erste Bank Retail",
      "Finom",
      "GRÁNIT Bank",
      "HSBCnet",
      "ING Wholesale Banking",
      "K&H Bank",
      "KDB Bank",
      "Lunar",
      "MagNet Bank",
      "MKB Bank (MBH Bank Nyrt)",
      "Monese",
      "N26 Bank",
      "Neteller",
      "Oberbank",
      "OTP Bank",
      "PayPal",
      "Paysera",
      "Raiffeisen Bank",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Takarékbank (MBH Bank Nyrt)",
      "Unicredit Bank Hungary Zrt.",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "IS",
    "name": "Iceland",
    "slug": "iceland",
    "bankCount": 20,
    "banks": [
      "Airwallex",
      "Arion Bank",
      "bunq",
      "Finom",
      "HSBCnet",
      "Islandsbanki",
      "Landsbankinn",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "IE",
    "name": "Ireland",
    "slug": "ireland",
    "bankCount": 27,
    "banks": [
      "Airwallex",
      "Allied Irish Banks",
      "Allied Irish Banks Corporate",
      "Bank of Ireland 365 Online",
      "Bank of Ireland Business On Line",
      "Barclays",
      "bunq",
      "EBS",
      "Finom",
      "Fire",
      "HSBCnet",
      "ING Wholesale Banking",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Permanent TSB",
      "Pleo",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "IT",
    "name": "Italy",
    "slug": "italy",
    "bankCount": 403,
    "banks": [
      "Airwallex",
      "Alto Adige Banca – Sudtirol Bank",
      "Banca Adria Colli Euganei",
      "Banca Agricola Popolare di Ragusa",
      "Banca Agricola Popolare di Ragusa Corporate",
      "Banca AideXa",
      "Banca Akros",
      "Banca Aletti",
      "Banca Alpi Marittime Carrù",
      "Banca Alta Toscana",
      "Banca Alto Vicentino Credito Cooperativo Di Schio, Pedemonte E Roana",
      "Banca Annia Cred. Coop. Cartura E Polesine",
      "Banca Centro – Credito Cooperativo Toscana – Umbria Soc. Coop",
      "Banca Centro Emilia",
      "Banca Centro Lazio",
      "Banca Centropadana",
      "Banca Cesare Ponti",
      "Banca Cremasca E Mantovana",
      "Banca Dei Sibillini, Credito Cooperativo Di Casavecchia",
      "Banca del Fucino",
      "Banca del Fucino Corporate",
      "Banca del Mezzogiorno – MedioCredito Centrale",
      "Banca del Piemonte",
      "Banca del Piemonte Corporate",
      "Banca del Sud",
      "Banca Del Territorio Lombardo",
      "Banca Dell´elba",
      "Banca Della Marca",
      "Banca Della Valsassina",
      "Banca Delle Terre Venete",
      "Banca Di Ancona E Falconara Marittima",
      "Banca Di Andria",
      "Banca Di Anghiari E Stia",
      "Banca Di Bologna",
      "Banca Di Caraglio, Del Cuneese E Della Riviera Dei Fiori",
      "Banca di Cividale",
      "Banca di Cividale Corporate",
      "Banca Di Credito Cooperativo Bergamasca E Orobica",
      "Banca Di Credito Cooperativo Cassa Rurale Di Val Di Fiemme",
      "Banca Di Credito Cooperativo Dei Castelli E Degli Iblei",
      "Banca Di Credito Cooperativo Dei Castelli Romani",
      "Banca Di Credito Cooperativo Del Circeo E Privernate",
      "Banca Di Credito Cooperativo Del Friuli Centrale",
      "Banca Di Credito Cooperativo Dell'alta Murgia",
      "Banca Di Credito Cooperativo Dell'alto Tirreno Della Calabria Verbicaro",
      "Banca Di Credito Cooperativo Della Romagna Occidentale",
      "Banca Di Credito Cooperativo Delle Prealpi",
      "Banca Di Credito Cooperativo Di Alba, Langhe, Roero E Del Canavese",
      "Banca Di Credito Cooperativo Di Alberobello E Sammichele Di Bari",
      "Banca Di Credito Cooperativo Di Anagni",
      "Banca Di Credito Cooperativo Di Aquara",
      "Banca Di Credito Cooperativo Di Avetrana",
      "Banca Di Credito Cooperativo Di Barlassina",
      "Banca Di Credito Cooperativo Di Brescia Di Brescia",
      "Banca Di Credito Cooperativo Di Casalgrasso E Sant'albano Stura",
      "Banca Di Credito Cooperativo Di Cassano Delle Murge E Tolve",
      "Banca Di Credito Cooperativo Di Castagneto Carducci Soc. Coop. Per Azioni",
      "Banca Di Credito Cooperativo Di Cherasco",
      "Banca Di Credito Cooperativo Di Conversano",
      "Banca Di Credito Cooperativo Di Filottrano - Credito Cooperativo Di Filottrano E Camerano",
      "Banca Di Credito Cooperativo Di Flumeri",
      "Banca Di Credito Cooperativo Di Locorotondo Cassa Rurale Ed Artigiana",
      "Banca Di Credito Cooperativo Di Marina Di Ginosa",
      "Banca Di Credito Cooperativo Di Oppido Lucano E Ripacandida",
      "Banca Di Credito Cooperativo Di Pianfei E Rocca De' Baldi",
      "Banca Di Credito Cooperativo Di Recanati E Colmurano",
      "Banca Di Credito Cooperativo Di San Giovanni Rotondo",
      "Banca Di Credito Cooperativo Di San Marco Dei Cavoti E Del Sannio",
      "Banca Di Credito Cooperativo Di San Marzano Di San Giuseppe",
      "Banca Di Credito Cooperativo Di Santeramo In Colle",
      "Banca Di Credito Cooperativo Di Sarsina",
      "Banca Di Credito Cooperativo Di Scafati E Cetara",
      "Banca Di Credito Cooperativo Di Spello E Bettona",
      "Banca di Credito Cooperativo di Spinazzola",
      "Banca Di Credito Cooperativo Di Staranzano E Villesse",
      "Banca Di Credito Cooperativo La Riscossa Di Regalbuto",
      "Banca Di Credito Cooperativo Laudense Lodi",
      "Banca Di Credito Cooperativo Monte Pruno Di Roscigno E Di Laurino",
      "Banca Di Credito Cooperativo Sangro Taetina Di Atessa Castiglione Giuliano",
      "Banca Di Credito Cooperativo Valdostana",
      "Banca Di Credito Cooperativo Valle Del Torto",
      "Banca di Credito Peloritano",
      "Banca di Credito Peloritano Corporate",
      "Banca di Credito Popolare di Torre del Greco",
      "Banca di Credito Popolare di Torre del Greco Corporate",
      "Banca di Imola",
      "Banca di Imola Corporate",
      "Banca di Macerata",
      "Banca Di Pesaro",
      "Banca Di Pescia E Cascina",
      "Banca Di Pisa E Fornacette Credito Cooperativo",
      "Banca Di Ripatransone E Del Fermano",
      "Banca di Risparmio di Savigliano",
      "Banca Di Taranto Bcc",
      "Banca Di Udine",
      "Banca Di Verona E Vicenza",
      "Banca Don Rizzo - Credito Cooperativo Della Sicilia Occidentale",
      "Banca Euromobiliare",
      "Banca Fideuram",
      "Banca Finnat Euramerica",
      "Banca Finnat Euramerica Corporate",
      "Banca Galileo",
      "Banca Generali",
      "Banca Generali Corporate",
      "Banca Ifis",
      "Banca Intermobiliare",
      "Banca Intermobiliare Corporate",
      "Banca Lazio Nord Credito Cooperativo Soc. Coop. Per Azioni",
      "Banca Malatestiana",
      "Banca Mediocredito Del Friuli Venezia Giulia",
      "Banca Mediolanum",
      "Banca Mediolanum Corporate",
      "Banca Monte dei Paschi di Siena Corporate",
      "Banca Monte dei Paschi di Siena Retail",
      "Banca Nazionale del Lavoro",
      "Banca Nazionale del Lavoro Corporate",
      "Banca Passadore",
      "Banca Patavina Di Sant´elena E Piove Di Sacco",
      "Banca Patrimoni",
      "Banca Popolare Del Cassinate Società Cooperativa Per Azioni",
      "Banca Popolare del Frusinate",
      "Banca Popolare del Frusinate Corporate",
      "Banca Popolare del Lazio",
      "Banca Popolare del Lazio Corporate",
      "Banca Popolare Delle Provincie Molisane",
      "Banca Popolare Di Cortona Soc. Coop. Per Azioni",
      "Banca Popolare di Fondi",
      "Banca Popolare di Fondi Corporate",
      "Banca Popolare Di Lajatico",
      "Banca Popolare Pugliese",
      "Banca Popolare Pugliese Corporate",
      "Banca Popolare Valconca",
      "Banca Popolare Valconca Corporate",
      "Banca Popolare Vesuviana",
      "Banca Privata Leasing",
      "Banca Privata Leasing Corporate",
      "Banca Progetto",
      "Banca Promos",
      "Banca San Francesco",
      "Banca Sant'Angelo",
      "Banca Sant'Angelo Corporate",
      "Banca Santa Giulia",
      "Banca Sella",
      "Banca Sicana Di Sommatino, Serradifalco E Sambuca Di Sicilia",
      "Banca Stabiese",
      "Banca Sviluppo",
      "Banca Tema",
      "Banca Ubae",
      "Banca Valsabbina",
      "Banca Valsabbina Corporate",
      "Banca Veronese",
      "Banca Versilia Lunigiana E Garfagnana",
      "Banca Widiba",
      "Bancater Credito Cooperativo Fvg",
      "Banco BPM Corporate",
      "Banco BPM WeBank",
      "Banco BPM YouWeb",
      "Banco di Desio e della Brianza",
      "Banco di Desio e della Brianza Corporate",
      "Banco di Desio e della Brianza Corporate IBK",
      "Banco di Lucca e del Tirreno",
      "Banco di Lucca e del Tirreno Corporate",
      "Banco di Sardegna Corporate",
      "Banco di Sardegna Smart",
      "Banco Fiorentino-mugello Impruneta Signa",
      "Banco Marchigiano Credito Cooperativo",
      "Banque Chaabi du Maroc",
      "Barclays Bank Ireland PLC Sede Secondaria",
      "BCC 'G. Toniolo' Di San Cataldo",
      "BCC Abruzzese Cappelle Sul Tavo",
      "BCC Agrigentino",
      "BCC Agrobresciano",
      "Bcc Basilicata Credito Cooperativo Di Laurenzana E Comuni Lucani",
      "BCC Brianza E Laghi",
      "BCC Campania Centro CRA",
      "BCC Canosa Loconia",
      "BCC CRA Di Paliano",
      "BCC Degli Ulivi Terra Di Bari",
      "BCC Dei Colli Albani",
      "BCC Del Basso Sebino",
      "BCC Del Garda - BCC Colli Morenici Del Garda",
      "BCC Del Metauro",
      "BCC Del Piceno",
      "BCC Del Valdarno",
      "BCC Dell´adriatico Teramano",
      "BCC Dell´oglio E Del Serio",
      "BCC Della Calabria Ulteriore",
      "BCC Della Valle Del Trigno",
      "BCC Delle Madonie",
      "BCC Di Altofonte E Caccamo",
      "BCC Di Arborea",
      "BCC Di Bari",
      "BCC Di Basciano",
      "BCC Di Borghetto Lodigiano",
      "BCC Di Buccino E Dei Comuni Cilentani",
      "BCC Di Busto Garolfo E Buguggiate",
      "BCC Di Cagliari",
      "BCC Di Capaccio Paestum E Serino",
      "BCC Di Carate Brianza",
      "BCC Di Caravaggio Adda E Cremasco",
      "BCC Di Castiglione Messer Raimondo E Pianella",
      "BCC Di Cittanova",
      "BCC Di Fano",
      "BCC Di Gambatesa",
      "BCC Di Gaudiano Di Lavello",
      "BCC Di Lezzeno",
      "BCC Di Milano",
      "BCC Di Montepaone",
      "BCC Di Mozzanica",
      "BCC Di Napoli",
      "BCC Di Nettuno",
      "BCC Di Ostra E Morro D´alba",
      "BCC Di Ostra Vetere",
      "BCC Di Ostuni",
      "BCC Di Pachino",
      "BCC Di Pergola E Corinaldo",
      "BCC Di Pontassieve",
      "BCC Di Pratola Peligna",
      "BCC Di Putignano",
      "BCC Di Roma",
      "BCC Di San Calogero E Maierato - BCC Del Vibonese",
      "BCC Di Spinazzola",
      "BCC Di Terra D´otranto",
      "BCC Di Triuggio E Della Valle Del Lambro",
      "Bcc Felsinea BCC Dal 1902",
      "BCC Leverano",
      "BCC Longi Valle Del Fitalia R.l.",
      "BCC Mediocrati",
      "BCC Pordenonese E Monsile",
      "BCC Provincia Romana",
      "BCC Terra Di Lavoro S. Vincenzo De´ Paoli",
      "BCC Valdarno Fiorentino Banca Di Cascia",
      "BCC Valpolicella Benaco Banca",
      "BCC Vicentino Pojana Maggiore",
      "BDM BANCA S.p.A.",
      "Bene Banca Credito Cooperativo Di Bene Vagienna",
      "Blu Banca",
      "Blu Banca Corporate",
      "BPER Banca Corporate",
      "BPER Banca Smart",
      "bunq",
      "Cassa Centrale Banca",
      "Cassa di Risparmio di Asti",
      "Cassa di Risparmio di Asti Corporate",
      "Cassa di Risparmio di Bolzano",
      "Cassa di Risparmio di Fermo",
      "Cassa di Risparmio di Fermo Corporate",
      "Cassa di Risparmio di Fossano",
      "Cassa di risparmio di Orvieto",
      "Cassa di Risparmio di Volterra",
      "Cassa di Sovvenzioni e Risparmio",
      "Cassa Lombarda",
      "Cassa Padana BCC",
      "Cassa Raiffeisen Di San Martino In Passiria",
      "Cassa Rurale Alta Vallagarina Di Besenello, Calliano, Nomi, Volano BCC",
      "Cassa Rurale Alta Valsugana BCC",
      "Cassa Rurale Alto Garda BCC",
      "Cassa Rurale BCC Di Treviglio",
      "Cassa Rurale Della Bassa Valsugana BCC",
      "Cassa Rurale Di Ledro BCC",
      "Cassa Rurale Di Trento BCC",
      "Cassa Rurale Dolomiti Di Fassa Primiero E Belluno BCC",
      "Cassa Rurale Ed Artigiana Di Boves BCC",
      "Cassa Rurale Ed Artigiana Di Cortina D'ampezzo E Delle Dolomiti",
      "Cassa Rurale Giudicarie Valsabbia Paganella BCC",
      "Cassa Rurale Novella E Alta Anaunia BCC",
      "Cassa Rurale Renon",
      "Cassa Rurale Rotaliana E Giovo BCC",
      "Cassa Rurale Val Di Non BCC",
      "Cassa Rurale Val Di Sole BCC",
      "Cassa Rurale Vallagarina BCC",
      "Centromarca Banca - Credito Cooperativo Di Treviso E Venezia",
      "Centroveneto Bassano Banca",
      "Cereabanca 1897",
      "Chebanca! Corporate",
      "Cherry Bank S.p.A.",
      "Cherry Bank S.p.A. Corporate",
      "Chiantibanca",
      "CRA Castellana Grotte",
      "CRA Di Binasco",
      "CRA Di Cantù BCC",
      "CRA Di Rivarolo Mantovano",
      "CREDEM Corporate",
      "CREDEM Retail",
      "Crédit Agricole Internet Banking PMI SBW",
      "Crédit Agricole Internet Banking PMI-Net2 Corporate",
      "Crédit Agricole Internet Banking Private HBW",
      "Credit Suisse",
      "Credito Cooperativo Cassa Rurale Ed Artigiana Del Friuli Venezia Giulia",
      "Credito Cooperativo Cassa Rurale Ed Artigiana Di Erchie",
      "Credito Cooperativo Centro Calabria",
      "Credito Cooperativo Friuli",
      "Credito Cooperativo Ravennate Forlivese E Imolese",
      "Credito Cooperativo Romagnolo - BCC Di Cesena E Gatteo",
      "Credito Etneo BCC",
      "Credito Lombardo Veneto",
      "Credito Padano BCC",
      "Deutsche Bank",
      "Deutsche Bank Corporate",
      "DOTS",
      "Ebury",
      "Emil Banca",
      "Extrabanca",
      "Extrabanca Corporate",
      "Findomestic Banca",
      "Fineco",
      "Finom",
      "Friulovest Banca",
      "Guber Banca",
      "Hello Bank!",
      "HSBCnet",
      "Hype",
      "Hype Business",
      "Hypo Tirol Bank",
      "IBL Banca",
      "IGEA Digital Bank",
      "Illimity",
      "Imprebanca",
      "Imprebanca Corporate",
      "ING",
      "ING Wholesale Banking",
      "Intesa Sanpaolo",
      "Intesa Sanpaolo InBiz",
      "Intesa Sanpaolo Private",
      "Istituto per il Credito Sportivo",
      "Isybank",
      "La Banca Del Crotonese",
      "La Cassa di Ravenna",
      "La Cassa di Ravenna Corporate",
      "LIS Pay",
      "LIS Pay Corporate",
      "Lunar",
      "Mediobanca Banca di Credito Finanziario",
      "Mediobanca Premier",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Poste Italiane - Banco Posta",
      "Poste Italiane - Banco Posta Corporate",
      "PostePay",
      "Prader Bank ",
      "Qonto",
      "Raiffeisen Landesbank Sudtirol AG",
      "Raiffeisenkasse Algund",
      "Raiffeisenkasse Bruneck",
      "Raiffeisenkasse Deutschnofen-Aldein",
      "Raiffeisenkasse Eisacktal",
      "Raiffeisenkasse Etschtal",
      "Raiffeisenkasse Freienfeld",
      "Raiffeisenkasse Groden",
      "Raiffeisenkasse Hochpustertal",
      "Raiffeisenkasse Kastelruth - St. Ulrich",
      "Raiffeisenkasse Laas",
      "Raiffeisenkasse Lana",
      "Raiffeisenkasse Latsch",
      "Raiffeisenkasse Marling",
      "Raiffeisenkasse Meran",
      "Raiffeisenkasse Niederdorf",
      "Raiffeisenkasse Obervinschgau",
      "Raiffeisenkasse Partschins",
      "Raiffeisenkasse Passeier",
      "Raiffeisenkasse Prad Taufers",
      "Raiffeisenkasse Salurn",
      "Raiffeisenkasse Sarntal",
      "Raiffeisenkasse Schenna",
      "Raiffeisenkasse Schlanders",
      "Raiffeisenkasse Schlern-Rosengarten",
      "Raiffeisenkasse Tauferer Arnthal",
      "Raiffeisenkasse Tirol",
      "Raiffeisenkasse Tisens",
      "Raiffeisenkasse Toblach",
      "Raiffeisenkasse Uberetsch",
      "Raiffeisenkasse Ulten-St.Pankraz- Laurein",
      "Raiffeisenkasse Untereisacktal",
      "Raiffeisenkasse Unterland",
      "Raiffeisenkasse Untervinschgau",
      "Raiffeisenkasse Val Badia",
      "Raiffeisenkasse Villnoss",
      "Raiffeisenkasse Vintl",
      "Raiffeisenkasse Welsberg-Gsies-Taisten",
      "Raiffeisenkasse Wipptal",
      "Revolut",
      "Riviera Banca Credito Cooperativo Di Rimini E Gradata",
      "Romagnabanca",
      "Rovigo Banca",
      "SANFELICE 1893 Banca Popolare",
      "SANFELICE 1893 Banca Popolare Corporate",
      "Sella Personal Credit",
      "Skrill",
      "Soldo",
      "Solution Bank",
      "Stripe",
      "Swan",
      "tot.",
      "UBS",
      "Unicredit",
      "Unicredit - Buddy Bank",
      "Vivid Money",
      "Volkswagen Bank",
      "Wise",
      "Zadruzna Kraska Banka Trst Gorica Zadruga"
    ]
  },
  {
    "code": "LV",
    "name": "Latvia",
    "slug": "latvia",
    "bankCount": 26,
    "banks": [
      "Airwallex",
      "BluOr",
      "Citadele",
      "Finom",
      "HSBCnet",
      "Industra Bank",
      "Luminor",
      "Lunar",
      "Magnetiq Bank",
      "Monese",
      "N26 Bank",
      "Neteller",
      "OP Corporate Bank",
      "PayPal",
      "Paysera",
      "Revolut",
      "Rietumu Banka",
      "SEB",
      "Signet Bank",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Swedbank",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "LI",
    "name": "Liechtenstein",
    "slug": "liechtenstein",
    "bankCount": 17,
    "banks": [
      "Airwallex",
      "bunq",
      "Finom",
      "HSBCnet",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "LT",
    "name": "Lithuania",
    "slug": "lithuania",
    "bankCount": 25,
    "banks": [
      "Airwallex",
      "Artea (Šiaulių bankas)",
      "Citadele",
      "ConnectPay",
      "Finom",
      "HSBCnet",
      "International Business Settlement",
      "Luminor",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "OP Corporate Bank",
      "PayPal",
      "Paysera",
      "Revolut",
      "SEB",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Swedbank",
      "Urbo",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "LU",
    "name": "Luxembourg",
    "slug": "luxembourg",
    "bankCount": 49,
    "banks": [
      "Airwallex",
      "Banco Safra",
      "Banco Santander",
      "Bankinter",
      "Banque de Luxembourg",
      "Banque de Luxembourg Belgique",
      "Banque et Caisse d’Epargne de l’Etat",
      "Banque Internationale a Luxembourg",
      "Banque Populaire ALC Succursale du Luxembourg",
      "Banque Raiffeisen",
      "Banque Transatlantique",
      "BGL BNP Paribas",
      "BPER Bank Luxembourg S.A.",
      "bunq",
      "Deutsche Bank",
      "DNB",
      "East-West United Bank",
      "EFG Bank",
      "Eurobank Private Bank",
      "Finom",
      "Goldman Sachs",
      "HSBCnet",
      "ING",
      "ING Wholesale Banking",
      "Julius Baer",
      "Lombard Odier",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Pictet",
      "Post Luxembourg",
      "Quintet Private Bank",
      "Revolut",
      "Royal Bank of Scotland International ClearSpend",
      "Royal Bank of Scotland International EQ",
      "SEB",
      "Skrill",
      "Societe Generale Corporate",
      "Soldo",
      "Stripe",
      "Swan",
      "UBS",
      "Union Bancaire Privée",
      "Union Bancaire Privée Europe",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "MT",
    "name": "Malta",
    "slug": "malta",
    "bankCount": 18,
    "banks": [
      "Airwallex",
      "Bank of Valletta",
      "bunq",
      "Finom",
      "HSBCnet",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "NL",
    "name": "Netherlands",
    "slug": "netherlands",
    "bankCount": 31,
    "banks": [
      "ABN AMRO Bank",
      "Airwallex",
      "ASN Bank",
      "bunq",
      "Ebury",
      "Finom",
      "Handelsbanken Corporate",
      "Handelsbanken Private",
      "HSBCnet",
      "ING",
      "ING Wholesale Banking",
      "KBC",
      "Knab",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Qonto",
      "Rabobank",
      "RegioBank",
      "Revolut",
      "Skrill",
      "SNS Bank",
      "Soldo",
      "Stripe",
      "Swan",
      "Triodos Bank",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "NZ",
    "name": "New Zealand",
    "slug": "new-zealand",
    "bankCount": 6,
    "banks": [
      "ANZ",
      "ASB",
      "BNZ",
      "Kiwibank",
      "NZHL",
      "Westpac"
    ]
  },
  {
    "code": "NO",
    "name": "Norway",
    "slug": "norway",
    "bankCount": 141,
    "banks": [
      "Aasen Sparebank",
      "Airwallex",
      "Andebu Sparebank",
      "Arendal og Omegns Sparekasse",
      "Askim og Spydeberg Sparebank",
      "Aurskog Sparebank",
      "Bank Norwegian",
      "Bank2",
      "Berg Sparebank",
      "Bien Sparebank",
      "Bjugn Sparebank",
      "Blaker Sparebank",
      "BN Bank ASA",
      "BoligBanken",
      "bunq",
      "Circle K Mastercard",
      "Cultura",
      "Danske Bank Business",
      "Danske Bank Private",
      "DNB",
      "Drangedal og Tørdal Sparebank",
      "Eidsberg Sparebank",
      "Entercard",
      "Esso",
      "Etnedal Sparebank",
      "Eurocard",
      "Eurocard Corporate",
      "Evje og Hornnes Sparebank",
      "Facitbank NO",
      "Fana Sparebank",
      "Finnair Mastercard",
      "Finom",
      "Flekkefjord Sparebank",
      "Forsvarets Personell Service",
      "Gildeskål Sparebank",
      "GlobeCard",
      "Grong Sparebank",
      "Grue Sparebank",
      "Haltdalen Sparebank",
      "Handelsbanken",
      "Hegra Sparebank",
      "Høland og Setskog Sparebank",
      "HSBCnet",
      "Ikano Bank",
      "Jæren Sparebank",
      "KLP Banken",
      "Kvinesdal Sparebank",
      "Landkreditt Bank AS",
      "Landkreditt Mastercard",
      "Larvikbanken Brunlanes Sparebank",
      "Lillesands Sparebank",
      "Lunar",
      "Luster Sparebank",
      "Maritime & Merchant Bank",
      "Marker Sparebank",
      "Melhus Sparebank",
      "Monese",
      "Morrow Bank",
      "MyBank ASA",
      "N26 Bank",
      "Næringsbanken",
      "Neteller",
      "Nidaros Sparebank",
      "Nordea Business",
      "Nordea Corporate",
      "Nordea Personal",
      "Nordic Choice Club",
      "Nordic Corporate Bank",
      "OBOS-banken AS",
      "Odal Sparebank",
      "Oppdalsbanken",
      "Orkla Sparebank",
      "Ørland Sparebank",
      "Ørskog Sparebank",
      "Oslofjord Sparebank",
      "Østre Agder Sparebank",
      "Pareto Bank ASA",
      "PayPal",
      "Paysera",
      "Resurs Bank",
      "Revolut",
      "Rogaland Sparebank",
      "Romerike Sparebank",
      "RørosBanken",
      "SAS Mastercard",
      "SEB",
      "SEB Kort Bank AB",
      "SEB Kort Bank AB Corporate",
      "SEB Selected Mastercard",
      "Selbu Sparebank",
      "Skagerrak Sparebank",
      "Skrill",
      "Skudenes & Aakra Sparebank",
      "Skue Sparebank",
      "Sogn Sparebank",
      "Søgne og Greipstad Sparebank",
      "Soknedal Sparebank",
      "Soldo",
      "Sparebank 1 Gudbrandsdal",
      "Sparebank 1 Hallingdal Valdres",
      "Sparebank 1 Helgeland",
      "Sparebank 1 Lom og Skjåk",
      "Sparebank 1 Nord-Norge",
      "Sparebank 1 Nordvest",
      "SpareBank 1 Østfold Akershus",
      "SpareBank 1 Østlandet",
      "Sparebank 1 Ringerike Hadeland",
      "Sparebank 1 SMN",
      "SpareBank 1 Sørøst-Norge",
      "Sparebank 1 SR-Bank",
      "Sparebank 68 Nord",
      "Sparebanken DIN",
      "Sparebanken Møre",
      "Sparebanken Narvik",
      "Sparebanken Norge",
      "Sparebanken Norge (Sør)",
      "Sparebanken Norge Corporate",
      "Sparebanken Øst",
      "Sparebanken Sogn og Fjordane",
      "Spareskillingsbanken",
      "Stadsbygd Sparebank",
      "Storebrand",
      "Stripe",
      "Strømmen Sparebank",
      "Sunndal Sparebank",
      "Swan",
      "Swedbank",
      "Tolga-Os Sparebank",
      "Totens Sparebank",
      "Trøgstad Sparebank",
      "Trondelag Sparebank",
      "Trondelag Sparebank",
      "Tysnes Sparebank",
      "Valdres Sparebank",
      "Valle Sparebank",
      "Vekselbanken",
      "Vivid Money",
      "Volvo kortet Mastercard",
      "Voss Sparebank",
      "Wise",
      "yA Bank"
    ]
  },
  {
    "code": "PL",
    "name": "Poland",
    "slug": "poland",
    "bankCount": 34,
    "banks": [
      "Aion Bank",
      "Airwallex",
      "Alior Bank",
      "Bank Millennium",
      "Bank Pekao",
      "BNP Paribas",
      "BNP Paribas Corporate",
      "Ebury",
      "Erste Bank Polska",
      "Erste Bank Polska Corporate",
      "Finom",
      "HSBCnet",
      "Ikano Bank",
      "ING",
      "Inteligo",
      "Lunar",
      "mBank Corporate",
      "mBank Retail",
      "Monese",
      "N26 Bank",
      "Nest Bank Corporate",
      "Nest Bank Private",
      "Neteller",
      "PayPal",
      "Paysera",
      "PKO Bank Polski",
      "PKO Bank Polski iPKO Biznes",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "PT",
    "name": "Portugal",
    "slug": "portugal",
    "bankCount": 47,
    "banks": [
      "Abanca",
      "Abanca Corporate",
      "Airwallex",
      "Banco ActivoBank",
      "Banco Atlantico Europa",
      "Banco BPI",
      "Banco Carregosa",
      "Banco de Investimento Global",
      "Banco Portugues de Gestao",
      "Banco Santander",
      "Bankinter",
      "BBVA",
      "bunq",
      "Caixa Central de Credito Agricola Mutuo",
      "Caixa De Credito Agricola Mutuo Da Chamusca",
      "Caixa De Credito Agricola Mutuo De Bombarral",
      "Caixa de Credito Agricola Mutuo de Leiria",
      "Caixa de Credito Agricola Mutuo de Mafra",
      "Caixa De Credito Agricola Mutuo De Torres Vedras",
      "Caixa Economica da Misericordia de Angra do Heroismo",
      "Caixa Economica Montepio Geral",
      "Caixa Geral De Depositos",
      "Cetelem",
      "COFIDIS",
      "Ebury",
      "Finom",
      "HSBCnet",
      "ING Wholesale Banking",
      "Lunar",
      "Millennium BCP",
      "Monese",
      "N26 Bank",
      "Neteller",
      "Nickel Beta",
      "Novo Banco",
      "Novo Banco Dos Açores",
      "PayPal",
      "Paysera",
      "Qonto",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Unicre - Instituição Financeira de Crédito",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "RO",
    "name": "Romania",
    "slug": "romania",
    "bankCount": 31,
    "banks": [
      "Airwallex",
      "Banca Comercială Română",
      "Banca Transilvania",
      "BRD Groupe Societe Generale",
      "BRD Groupe Societe Generale Corporate",
      "bunq",
      "CEC Bank",
      "Finom",
      "Garanti BBVA",
      "HSBCnet",
      "ING",
      "ING Wholesale Banking",
      "Libra Bank",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "PayPal",
      "Paysera",
      "Porsche Bank",
      "ProCredit Bank",
      "Raiffeisen Bank",
      "Raiffeisen Bank Corporate",
      "Revolut",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Unicredit",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "SK",
    "name": "Slovakia",
    "slug": "slovakia",
    "bankCount": 28,
    "banks": [
      "Airwallex",
      "bunq",
      "Československá obchodní banka",
      "Finom",
      "Fio banka",
      "HSBCnet",
      "ING Wholesale Banking",
      "Lunar",
      "mBank Retail",
      "Monese",
      "N26 Bank",
      "Neteller",
      "Oberbank",
      "PayPal",
      "Paysera",
      "Prima Banka",
      "Raiffeisen Banka",
      "Revolut",
      "Skrill",
      "Slovenská sporiteľňa",
      "Soldo",
      "Stripe",
      "Swan",
      "Tatra Banka",
      "Unicredit",
      "Vivid Money",
      "VUB Banka",
      "Wise"
    ]
  },
  {
    "code": "SI",
    "name": "Slovenia",
    "slug": "slovenia",
    "bankCount": 29,
    "banks": [
      "Addiko Bank",
      "Airwallex",
      "BKS Bank AG",
      "bunq",
      "Delavska Hranilnica",
      "Deželna Banka Slovenije",
      "Finom",
      "Gorenjska Banka",
      "HSBCnet",
      "Intesa Sanpaolo",
      "LON",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "NLB Banka",
      "OTP Banka",
      "PayPal",
      "Paysera",
      "Primorska Hranilnica",
      "Revolut",
      "Skrill",
      "Soldo",
      "Sparkasse",
      "Stripe",
      "Swan",
      "Unicredit Banka Slovenija",
      "Vivid Money",
      "Wise"
    ]
  },
  {
    "code": "ES",
    "name": "Spain",
    "slug": "spain",
    "bankCount": 98,
    "banks": [
      "Abanca",
      "Abanca Corporate",
      "Activo Bank",
      "Airwallex",
      "Arquia Banca",
      "Banca March",
      "Banca Pueyo",
      "Banco de Investimento Global",
      "Banco de Sabadell",
      "Banco Europeo de Finanzas",
      "Banco Mediolanum",
      "Banco Pichincha",
      "Banco Santander",
      "Bank Norwegian",
      "Bankinter",
      "BBVA",
      "BCE",
      "bunq",
      "Caixa Guissona",
      "Caixa Popular",
      "Caixa Rural Benicarlo",
      "Caixa Rural de L'Alcudia",
      "Caixa Rural Galega",
      "CaixaBank",
      "Caja De Ingenieros",
      "Caja Rural Albal",
      "Caja Rural Algemesi",
      "Caja Rural Aragon",
      "Caja Rural Asturias",
      "Caja Rural Baena",
      "Caja Rural Cajaviva",
      "Caja Rural Cañete de las Torres",
      "Caja Rural de Casas Ibañez",
      "Caja Rural de Nueva Carteya",
      "Caja Rural del Sur",
      "Caja Rural El Salvador Vinaròs",
      "Caja Rural Extremadura",
      "Caja Rural Fuente Alamo",
      "Caja Rural Granada",
      "Caja Rural Jaen",
      "Caja Rural Navarra",
      "Caja Rural Onda",
      "Caja Rural Orihuela",
      "Caja Rural Salamanca",
      "Caja Rural San Isidro Les Coves",
      "Caja Rural San Isidro Vall D'Uxo",
      "Caja Rural San Jose Alcora",
      "Caja Rural San Jose de Almassora",
      "Caja Rural Soria",
      "Caja Rural Teruel",
      "Caja Rural Utrera",
      "Caja Rural Villamalea",
      "Caja Rural Zamora",
      "Cajalmendralejo",
      "Cajasiete",
      "CBNK Bank of Collectives SA",
      "Cetelem",
      "Colonya",
      "Credit Suisse",
      "Deutsche Bank",
      "Deutsche Bank Corporate",
      "Ebury",
      "Eurocaja Rural",
      "EVO Banco",
      "Fiare Banca Etica",
      "Finom",
      "Globalcaja",
      "Grupo Cajamar",
      "HSBCnet",
      "IberCaja",
      "ING",
      "ING Wholesale Banking",
      "Kutxabank",
      "Laboral Kutxa",
      "Lunar",
      "Monese",
      "N26 Bank",
      "Neteller",
      "Nickel Beta",
      "Openbank",
      "PayPal",
      "Paysera",
      "Pleo",
      "Qonto",
      "Renta 4 Banco",
      "Revolut",
      "Ruralnostra",
      "Santander Corporate & Investment Banking",
      "Self Bank",
      "Skrill",
      "Soldo",
      "Stripe",
      "Swan",
      "Triodos Bank",
      "Unicaja Banco",
      "Vivid Money",
      "Wise",
      "WiZink"
    ]
  },
  {
    "code": "SE",
    "name": "Sweden",
    "slug": "sweden",
    "bankCount": 85,
    "banks": [
      "Airwallex",
      "Ålandsbanken",
      "Bank Norwegian",
      "Bank Norwegian Decoupled",
      "bunq",
      "Circle K Mastercard",
      "Circle K Mastercard",
      "Coop Mastercard Mer",
      "Danske Bank Business",
      "Danske Bank Private",
      "Ekobanken Medlemsbank",
      "Entercard",
      "Eurocard",
      "Eurocard",
      "Eurocard Corporate",
      "Facitbank SE",
      "Finnair Mastercard",
      "Finnair Mastercard",
      "Finom",
      "Handelsbanken Corporate",
      "Handelsbanken Private",
      "HSBCnet",
      "ICA Banken",
      "Ikano Bank",
      "Ingo Mastercard",
      "Ingo Mastercard",
      "JAK Medlemsbank",
      "Lån & Spar Sverige",
      "Länsförsäkringar",
      "Lunar",
      "Monese",
      "Morrow Bank",
      "N26 Bank",
      "Neteller",
      "NK Nycklen Mastercard",
      "NK Nycklen Mastercard",
      "Nordea Business",
      "Nordea Corporate",
      "Nordea Personal",
      "Nordic Choice Club",
      "Nordic Choice Club",
      "OK-Q8 Bank",
      "Opel Mastercard",
      "Opel Mastercard",
      "PayPal",
      "Paysera",
      "Pleo",
      "Resurs Bank",
      "Revolut",
      "Saab Mastercard",
      "Saab Mastercard",
      "SAS Mastercard",
      "SAS Mastercard",
      "Scandic",
      "Scandic",
      "SEB Card Accounts",
      "SEB Card Accounts",
      "SEB Card Accounts Corporate",
      "SEB Card Accounts Corporate",
      "SEB Företag",
      "SEB Kort Bank AB",
      "SEB Kort Bank AB",
      "SEB Kort Bank AB Corporate",
      "SEB Kort Bank AB Corporate",
      "SEB Private",
      "SEB Selected Mastercard Corporate",
      "SEB Selected Mastercard Corporate",
      "SJ Prio Mastercard",
      "SJ Prio Mastercard",
      "Skandia Banken",
      "Skrill",
      "Soldo",
      "Sparbanken Syd",
      "Sparbankerna",
      "Sparbankerna Corporate",
      "Stripe",
      "SVEA Bank",
      "Swan",
      "Swedbank",
      "Swedbank Corporate",
      "Vivid Money",
      "Wallet",
      "Wallet",
      "Wise",
      "Ziklo Bank Decoupled"
    ]
  },
  {
    "code": "GB",
    "name": "United Kingdom",
    "slug": "united-kingdom",
    "bankCount": 118,
    "banks": [
      "ABN AMRO Bank Commercial",
      "Airwallex",
      "Allica Bank",
      "Allied Irish Banks",
      "Allied Irish Banks (NI)",
      "Allied Irish Banks Corporate",
      "Alpha FX",
      "Amazon card (Newday)",
      "American Express",
      "Aqua card (Newday)",
      "Arbuthnot Latham",
      "Argos card (Newday)",
      "Bank of Ireland 365 Online",
      "Bank of Ireland Business On Line",
      "Bank of Scotland Business",
      "Bank of Scotland Commercial",
      "Bank of Scotland Personal",
      "Barclaycard Commercial Payments",
      "Barclaycard UK",
      "Barclays Business",
      "Barclays Corporate",
      "Barclays Personal",
      "Barclays Wealth",
      "BBVA",
      "BIP card (Newday)",
      "Burton card (Newday)",
      "C. Hoare & Co",
      "CAF Bank",
      "Capital One",
      "Cater Allen",
      "Caxton",
      "Chase Bank",
      "Chelsea Building Society",
      "Citi Private Bank",
      "Coutts",
      "Coutts&Co ClearSpend",
      "Credit Suisse",
      "Cumberland Building Society",
      "Cynergy Bank",
      "Danske Bank Business",
      "Danske Bank Private",
      "Debenhams card (Newday)",
      "Dorothy Perkins card (Newday)",
      "Ebury",
      "Finom",
      "First Direct",
      "Fluid card (Newday)",
      "Ghana International Bank",
      "GoHenry",
      "Goldman Sachs",
      "Halifax Personal",
      "Handelsbanken Corporate",
      "Handelsbanken Private",
      "Hargreaves Lansdown Saving Limited",
      "House of Fraser card (Newday)",
      "HSBC Business",
      "HSBC Kinetic",
      "HSBC Personal",
      "HSBCnet",
      "ING Wholesale Banking",
      "Investec",
      "Lloyds Business",
      "Lloyds Commercial",
      "Lloyds Personal",
      "Lombard Odier",
      "Lunar",
      "Marbles card (Newday)",
      "Marks & Spencer",
      "MBNA Personal",
      "Metro Bank",
      "Mettle",
      "Monese",
      "Monzo",
      "N26 Bank",
      "Nationwide",
      "Natwest",
      "Natwest Bankline",
      "Natwest ClearSpend",
      "Natwest International",
      "Neteller",
      "Newpay card (Newday)",
      "Opus card (Newday)",
      "PayPal",
      "Paysera",
      "Pleo",
      "Pulse card (Newday)",
      "Revolut",
      "Royal Bank of Scotland",
      "Royal Bank of Scotland Bankline",
      "Royal Bank of Scotland ClearSpend",
      "Santander Business",
      "Santander Corporate",
      "Santander Personal",
      "Skrill",
      "smile",
      "Soldo",
      "Starling",
      "Stripe",
      "Sumitomo Mitsui Banking Corporation",
      "Tesco Bank",
      "The Co-Operative Bank Business",
      "The Co-Operative Bank Retail",
      "thinkmoney",
      "Tide",
      "Triodos Bank",
      "TSB Bank",
      "TUI card (Newday)",
      "UBS",
      "Ulster Bank",
      "Union Bancaire Privée London",
      "Unity Trust Bank",
      "Vanquis Bank",
      "Virgin Money - sort code starts with 05 or 82",
      "Virgin Money - sort code starts with 08",
      "Wallis card (Newday)",
      "Wise",
      "Yorkshire Building Society",
      "Zempler Bank"
    ]
  }
];

export function getSynciDirectoryCountry(countryCode: string) {
  return (
    synciDirectoryCountries.find((country) => country.code === countryCode) ??
    synciDirectoryCountries[0]!
  );
}

export function findSynciDirectoryBanks(countryCode: string, query: string) {
  const normalizedQuery = query.trim().toLocaleLowerCase();
  const country = getSynciDirectoryCountry(countryCode);

  if (!normalizedQuery) return country.banks;

  return country.banks.filter((bank) =>
    bank.toLocaleLowerCase().includes(normalizedQuery),
  );
}

export function synciDirectoryUrl(countryCode: string) {
  return SYNCI_DIRECTORY_URL + "/" + getSynciDirectoryCountry(countryCode).slug;
}
