[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["corepack enable"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm exec prisma generate",
  "pnpm run build"
]

[start]
cmd = "pnpm exec prisma db push && pnpm run start"
