/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as URouteRouteImport } from './routes/u/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as PRouteRouteImport } from './routes/p/route'
import { Route as NewRouteRouteImport } from './routes/new/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as PPostIdRouteImport } from './routes/p/$postId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as PPostIdEditRouteImport } from './routes/p/$postId.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const URouteRoute = URouteRouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PRouteRoute = PRouteRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRouteRoute = NewRouteRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => URouteRoute,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRouteRoute,
} as any)
const PPostIdEditRoute = PPostIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PPostIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/new': typeof NewRouteRouteWithChildren
  '/p': typeof PRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/explore': typeof AppExploreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/p/$postId': typeof PPostIdRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/about/': typeof AboutIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/login/': typeof LoginIndexRoute
  '/new/': typeof NewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$postId/edit': typeof PPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p': typeof PRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/explore': typeof AppExploreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/p/$postId': typeof PPostIdRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/about': typeof AboutIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/login': typeof LoginIndexRoute
  '/new': typeof NewIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$postId/edit': typeof PPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/new': typeof NewRouteRouteWithChildren
  '/p': typeof PRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/explore': typeof AppExploreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/p/$postId': typeof PPostIdRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/about/': typeof AboutIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/login/': typeof LoginIndexRoute
  '/new/': typeof NewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$postId/edit': typeof PPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/new'
    | '/p'
    | '/settings'
    | '/u'
    | '/explore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/explore'
    | '/blog/$slug'
    | '/demo/better-auth'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/p/$postId'
    | '/u/$username'
    | '/about/'
    | '/app/'
    | '/blog/'
    | '/login/'
    | '/new/'
    | '/settings/'
    | '/api/auth/$'
    | '/p/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p'
    | '/u'
    | '/explore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/explore'
    | '/blog/$slug'
    | '/demo/better-auth'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/p/$postId'
    | '/u/$username'
    | '/about'
    | '/app'
    | '/blog'
    | '/login'
    | '/new'
    | '/settings'
    | '/api/auth/$'
    | '/p/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/new'
    | '/p'
    | '/settings'
    | '/u'
    | '/explore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/explore'
    | '/blog/$slug'
    | '/demo/better-auth'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/p/$postId'
    | '/u/$username'
    | '/about/'
    | '/app/'
    | '/blog/'
    | '/login/'
    | '/new/'
    | '/settings/'
    | '/api/auth/$'
    | '/p/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  NewRouteRoute: typeof NewRouteRouteWithChildren
  PRouteRoute: typeof PRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  URouteRoute: typeof URouteRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u': {
      id: '/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof URouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/new/': {
      id: '/new/'
      path: '/'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof URouteRoute
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/p/$postId/edit': {
      id: '/p/$postId/edit'
      path: '/edit'
      fullPath: '/p/$postId/edit'
      preLoaderRoute: typeof PPostIdEditRouteImport
      parentRoute: typeof PPostIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface NewRouteRouteChildren {
  NewIndexRoute: typeof NewIndexRoute
}

const NewRouteRouteChildren: NewRouteRouteChildren = {
  NewIndexRoute: NewIndexRoute,
}

const NewRouteRouteWithChildren = NewRouteRoute._addFileChildren(
  NewRouteRouteChildren,
)

interface PPostIdRouteChildren {
  PPostIdEditRoute: typeof PPostIdEditRoute
}

const PPostIdRouteChildren: PPostIdRouteChildren = {
  PPostIdEditRoute: PPostIdEditRoute,
}

const PPostIdRouteWithChildren =
  PPostIdRoute._addFileChildren(PPostIdRouteChildren)

interface PRouteRouteChildren {
  PPostIdRoute: typeof PPostIdRouteWithChildren
}

const PRouteRouteChildren: PRouteRouteChildren = {
  PPostIdRoute: PPostIdRouteWithChildren,
}

const PRouteRouteWithChildren =
  PRouteRoute._addFileChildren(PRouteRouteChildren)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface URouteRouteChildren {
  UUsernameRoute: typeof UUsernameRoute
}

const URouteRouteChildren: URouteRouteChildren = {
  UUsernameRoute: UUsernameRoute,
}

const URouteRouteWithChildren =
  URouteRoute._addFileChildren(URouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  NewRouteRoute: NewRouteRouteWithChildren,
  PRouteRoute: PRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  URouteRoute: URouteRouteWithChildren,
  ExploreRoute: ExploreRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
